GNS3/gns3-registry

appliances/netem.gns3a

My first try on an appliance.
The parameter "port_name_format" is ignored, either I did it wrong or GNS3 V1.4.0b3 on linux doesn't handle that.

Add NETem appliance

---

README.rst
appliances/microcore-linux.gns3a
check.py
symbols/README.rst
symbols/linux_guest.svg
symbols/linux_guest.txt

Proposal for the symbol support:
* We can specify a symbol in the appliance via the symbol field (gui
will fallback to default symbol if not internet available)
* Contributor should provide the copyrights for the symbol
Fix #5

Custom symbol support (registry part)

---

packer/NETem/NETem.json
packer/NETem/scripts/NETem.sh
packer/NETem/scripts/hd-install.sh
packer/NETem/scripts/post_setup.sh
packer/NETem/scripts/serial.sh
packer/NETem/uploads/boot_script
packer/NETem/uploads/netem-conf.py

The packer scripts follows closely the tinycore-linux packer scripts. The main differences:
- removed packages provisioner, the change of the tcedir to hard disk is added to hd-install.sh
- added uploads provisioner
The NETem image contents has not changed compared to previous hand-made images, no new features (or bugs).

Packer scripts for NETem

---

appliances/netem.gns3a

Forgot to include the updated NETem appliance

Updated NETem appliance

---

appliances/checkpoint-gaia.gns3a

Checkpoint Gaia

---

appliances/bird.gns3a
packer/tinycore-linux/README.rst
packer/tinycore-linux/bird.json
packer/tinycore-linux/scripts/bird.sh

New BIRD appliance to solve issue https://github.com/GNS3/gns3-registry/issues/25
Tested with https://community.gns3.com/people/behlers/blog/2015/11/08/injecting-lots-of-routes-into-a-gns3-topology
Can't upload the image to sourceforge, so someone of the GNS3 core team has to create the image, upload it and adapt file size and md5sum.

BIRD appliance

---

.travis.yml
README.rst
appliances/hp-vsr1001.gns3a
appliances/juniper-vsrx.gns3a
check.py
check_urls.py

Fix #43 
@ehlers what did you think about that?

Fix check.py with feedbacks from @ehlers

---

appliances/openwrt.gns3a
schemas/appliance.json

compression added as enum. Most popular compression types for unix defined. Also some archive types for the windows oriented world, where compression-only is rare.

Add compression of direct download url

---

schemas/appliance.json

Synced the appliance schema

---

appliances/openbsd.gns3a
packer/openbsd/openbsd.json

OpenBSD 5.8

---

symbols/vRIN.svg
symbols/vRIN.txt

Added vRIN symbol and license

---

appliances/ostinato.gns3a
packer/tinycore-linux/README.rst
packer/tinycore-linux/scripts/ostinato-drone.sh
packer/tinycore-linux/scripts/ostinato.sh

Ostinato uses the updated tiny core GUI.

Ostinato uses tinycore-linux.json as packer base

---

symbols/loadbalancer.svg
symbols/loadbalancer.txt

It's based on the firewall and gateway symbol from GNS3.

Proposal of a loab balancer icon.

---

appliances/bigswitch-bigcloud-fabric.gns3a

I'm not sure about the RAM amount. The OS warn before
I don't put 16GB :P

Big Switch Big Cloud Fabric

---

appliances/alcatel-7750.gns3a

Fix #84 
In theory we should be able to use multiple core. But it's crash the OS.

Alcatel 7750 support

---

appliances/juniper-vsrx.gns3a

Upgrade to Juniper 15 since the 12 is no longer available to download

---

docker/dhcp/Dockerfile
docker/dhcp/README.rst
docker/dhcp/boot.sh

This container provide a basic DHCP server that you can drop
in your topology and configure.

A basic DHCP container.

---

docker/haproxy/Dockerfile
docker/haproxy/haproxy.cfg

Hi @noplay, a haproxy container for testing load balancing to web servers with a typical configuration example.

Add haproxy alpine container

---

appliances/fortimail.gns3a
appliances/fortimanager.gns3a
appliances/fortiweb.gns3a

Unfortunately, FortiWeb has VNC console only.

Added Fortinet appliances: FortiWeb, FortiMail, FortiManager

---

docker/endhost/Dockerfile
docker/endhost/start-ssh.sh

I included the following tools: openssh, mtr, nmap, iperf, socat, vim, nano, curl, links, iputils, rsync, bash.
The resulting image is 54.44 MB size.
The list can grow and users can use the TUI script [https://github.com/AJNOURI/Alpine_Image_Builder](https://github.com/AJNOURI/Alpine_Image_Builder) to build own image flavors.

General purpose Alpine-based endhost.

---

appliances/fortianalyzer.gns3a

Both versions have been imported and tested in my environment.

FortiAnalyzer added

---

appliances/fortiadc.gns3a

Tested locally. Boots well, web GUI is accessible.

Added FortiADC load balancer

---

appliances/pfsense.gns3a

Updated pfSense with version 2.3

---

appliances/cisco-asav.gns3a
appliances/cisco-iosv.gns3a
appliances/fortiadc.gns3a
appliances/fortianalyzer.gns3a
appliances/fortimail.gns3a
appliances/fortimanager.gns3a
appliances/fortiweb.gns3a
appliances/hp-vsr1001.gns3a

Prettify appliances and update product_url in fortianalyzer.gns3

---

appliances/chromium.gns3a
appliances/ntopng.gns3a
appliances/opendaylight.gns3a
appliances/openvswitch-management.gns3a
appliances/openvswitch.gns3a
check.py
prettify_appliances.py
schemas/appliance.json

Need by https://github.com/GNS3/gns3-gui/issues/945

Docker container support

---

check_urls.py

With docker container support the 'images' property is now optional.
Furthermore handle Ctrl-C nicely.

check_urls: 'images' property is now optional, handle Ctrl-C

---

docker/iou/boot.sh
packer/alpine-linux/alpine-linux.json
packer/alpine-linux/scripts/setup.sh
packer/tinycore-linux/scripts/internet.sh
patch_appliance.py
prettify_appliances.py

The (hopefully) last cleanup against this dreadful unbreakable space

Cleanup unbreakable space

---

appliances/exos.gns3a
appliances/kemp-vlm.gns3a

All 3 have been tested locally, they're working fine.

Added KEMP VLM & Extreme Networks EXOS

---

docker/haproxy/Dockerfile

Causes error during image building

/etc/haproxy already created during installation.

---

appliances/smoothwall.gns3a

Added Smoothwall firewall

---

appliances/sophos-utm.gns3a

Added Sophos UTM Home Edition

---

appliances/asterisk.gns3a

Thought I should give you something for dinner too. :)

Added Asterisk IP PBX

---

appliances/f5-bigip.gns3a

Updated F5 BIG-IP with new versions

---

appliances/brocade-vrouter.gns3a
appliances/brocade-vtm.gns3a

All devices & versions have been tested locally, they work fine.
Commit addresses #42

Added 2 Brocade devices

---

appliances/fortianalyzer.gns3a
appliances/fortigate.gns3a

Question related to the commit: #146

Updated versions for some Fortinet appliances

---

appliances/cisco-wsav.gns3a

New appliance: Cisco WSAv

---

appliances/ipterm.gns3a
appliances/webterm.gns3a

Forgot to update the appliance description.

Update ipterm/webterm appliance description

---

appliances/brocade-vtm.gns3a
appliances/citrix-netscaler-vpx.gns3a
appliances/exos.gns3a
appliances/fortiadc.gns3a
appliances/fortimail.gns3a
appliances/fortiweb.gns3a
appliances/kemp-vlm.gns3a
appliances/pfsense.gns3a
appliances/sophos-utm.gns3a
appliances/untangle.gns3a

Added Citrix NetScaler & updated some appliances with new releases

---

appliances/arista-veos.gns3a
appliances/clearos.gns3a
appliances/fortimanager.gns3a
appliances/loadbalancer_org-va.gns3a
appliances/packetfence-zen.gns3a

All 3 have been tested locally, they're working fine.

New appliances: ClearOS firewall, Loadbalancer.org VA, Packetfence ZEN & updated some templates

---

appliances/vrin.gns3a

I'll make the announcement after the merge. :)

Updated vRIN with new release

---

appliances/trendmicro-imsva.gns3a

**Important:** Though the installed system is a few GBs only, the appliance requires at least 120G HDD. I created a new empty200G.qcow2 that is available here: https://1drv.ms/u/s!AggbvpthOTJHhYJGHFkIh2Wk0PrPoQ
Could you upload it where the others are? Thanks.

New appliance: Trend Micro IMS VA

---

appliances/trendmicro-iwsva.gns3a

New appliance: Trend Micro InterScan Web Security VA

---

appliances/brocade-vtm.gns3a
appliances/cisco-wsav.gns3a
appliances/citrix-netscaler-vpx.gns3a
appliances/loadbalancer_org-va.gns3a

Reverts GNS3/gns3-registry#161

Revert "New Cisco Web Security releases + symbol fixes"

---

appliances/zentyal-server.gns3a

Added Zentyal Server

---

appliances/brocade-vtm.gns3a
appliances/mikrotik-chr.gns3a
appliances/openwrt-realview.gns3a

This goes to the master; only the new versions are added.

New releases: Brocade VTM, Mikrotik, OpenWrt Realview

---

appliances/brocade-vtm.gns3a
appliances/forticache.gns3a
appliances/mikrotik-chr.gns3a
appliances/openwrt-realview.gns3a

I don't know why it adds the commits of the last merge.

New appliance: FortiCache

---

appliances/freebsd.gns3a
appliances/mikrotik-chr.gns3a

I think this and the next commit in the availability branch will solve the problem.

New appliance: FreeBSD; fixing unreferenced image

---

appliances/fortigate.gns3a
appliances/proxmox-mg.gns3a

+updated FortiGate with new release.

New appliance: Proxmox Mail Gateway

---

appliances/kali-linux.gns3a
appliances/sophos-utm.gns3a
appliances/zentyal-server.gns3a

+fixed direct download link for Zentyal server.

New releases: Kali Linux, Sophos UTM

---

appliances/brocade-vrouter.gns3a
appliances/brocade-vtm.gns3a
appliances/cumulus-vx.gns3a
appliances/packetfence-zen.gns3a

New releases: Brocade vRouter & VTM, Cumulus, Packetfence

---

appliances/freenas.gns3a

New appliance: FreeNAS

---

appliances/cisco-csr1000v.gns3a

﻿﻿Router#sh ip int br
Interface              IP-Address      OK? Method Status                Protocol
GigabitEthernet1       unassigned      YES DHCP   up                    up      
GigabitEthernet2       unassigned      YES unset  administratively down down    
GigabitEthernet3       unassigned      YES unset  administratively down down    
GigabitEthernet4       unassigned      YES unset  administratively down down

csr1000v interface names start at 1

---

appliances/kerio-connect.gns3a
appliances/kerio-control.gns3a
appliances/kerio-operator.gns3a

All 3 have been tested locally, they're working fine.

New appliances: Kerio Connect, Control, and Operator

---

appliances/coreos.gns3a
appliances/fortiadc.gns3a
appliances/forticache.gns3a
appliances/fortimail.gns3a
appliances/mikrotik-chr.gns3a
appliances/sophos-utm.gns3a

CoreOS, FortiADC, FortiCache, FortiMail, Mikrotik, Sophos UTM

New software releases

---

appliances/cloudrouter.gns3a

Solves #33. Tested locally, works fine.

New appliance: CloudRouter

---

appliances/cloudrouter.gns3a
appliances/f5-bigip.gns3a
appliances/fortiadc.gns3a
appliances/fortianalyzer.gns3a
appliances/fortigate.gns3a
appliances/fortimanager.gns3a
appliances/freebsd.gns3a
appliances/juniper-vsrx.gns3a
appliances/kemp-vlm.gns3a
appliances/kerio-connect.gns3a
appliances/kerio-control.gns3a
appliances/kerio-operator.gns3a
appliances/mikrotik-chr.gns3a
appliances/packetfence-zen.gns3a
appliances/sophos-iview.gns3a
appliances/sophos-utm.gns3a
appliances/sophos-xg.gns3a
appliances/untangle.gns3a

New releases: FortiADC, FortiAnalyzer, FortiGate, FortiManager, Juniper vSRX, Kemp VLM, Sophos UTM, Sophos XG, Untangle

New appliance (Sophos iView) & new releases

---

appliances/coreos.gns3a
appliances/cumulus-vx.gns3a
appliances/hp-vsr1001.gns3a
appliances/mikrotik-chr.gns3a

Also reorganized HP VSR a bit to have the oldest release at the bottom.

New releases: CoreOS Cumulus VX, HP VSR, Mikrotik CHR

---

appliances/cisco-csr1000v.gns3a

Added Versions 16.3 and 16.4 as found on Cisco.com

Updated CSR 1000v Appliance

---

appliances/cisco-ise.gns3a

Updated existing Appliance file to support version 2.0.0.306

Updated ISE appliance to support version 2.0.0.306

---

appliances/juniper-vmx-vcp.gns3a
appliances/juniper-vmx-vfp.gns3a
appliances/juniper-vqfx-pfe.gns3a
appliances/juniper-vqfx-re.gns3a
symbols/juniper-vmx.svg
symbols/juniper-vmx.txt
symbols/juniper-vqfx.svg
symbols/juniper-vqfx.txt

Includes a proposed symbol, and two proposed appliances, one for the Virtual Control Plane (vCP) and one for the Virtual Forwarding Plane (vFP)

Proposed Juniper vMX Appliance

---

appliances/ostinato.gns3a

Removed v0.7.1 from the appliance

Ostinato v0.7.1 is no longer supported

---

appliances/juniper-vmx-vcp.gns3a
appliances/juniper-vmx-vfp.gns3a

vMX Appliances (vCP and vFP) with 17.1R1.8 Added

Added 17.1R1.8

---

appliances/brocade-vrouter.gns3a
appliances/clearos.gns3a
appliances/exos.gns3a
appliances/hp-vsr1001.gns3a
appliances/juniper-vmx-vcp.gns3a
appliances/juniper-vmx-vfp.gns3a
appliances/packetfence-zen.gns3a

New releases

---

appliances/zentyal-server.gns3a

The md5sum and filesize were updated to current values.

Image info updated

---

docker/openvswitch/Dockerfile

People might not be familiar with vi, it is better to have an altenative editor like nano.

Add nano editor to ovs

---

appliances/cisco-nxosv9k.gns3a
appliances/python2.gns3a
appliances/python3.gns3a

I've tested all 3 versions with the new bios image and the sata disk interface. They run well, boot time has been reduced significantly.

Added Cisco NX-OSv9k & Python containers

---

appliances/ipfire.gns3a

New appliance: IPFire

---

appliances/fortisandbox.gns3a
appliances/ipfire.gns3a

New appliance: FortiSandbox

---

appliances/fortisiem-super_worker.gns3a

New appliance: FortiSIEM

---

appliances/network_automation.gns3a
docker/network_automation/Dockerfile
docker/network_automation/README.md

Requested by David. As a test, I've built it in Docker Hub, based on my Github repo; import & boot works in my local GNS3 VM.
Don't forget to rename the container on Docker Hub from gns3_registry to network_automation. ;)

New appliance: Network Automation

---

appliances/checkpoint-gaia.gns3a
appliances/cumulus-vx.gns3a
appliances/pan-vm-fw.gns3a

+new Cumulus & Checkpoint releases
Thanks to Andrew Coleman!

New appliance: Palo Alto FW

---

appliances/pan-vm-fw.gns3a
symbols/pan-vm-fw.svg
symbols/pan-vm-fw.txt

1. Added 7.1.0 and 6.1.0 ESX versions (vmdk) to the Appliance
2. Added a proposed symbol for PA-VM
3. modified GNS3a file to use proposed symbol

PA-VM Appliance Proposed Changes

---

docker/network_automation/Dockerfile

The distro provided Ansible was too old (2.0.0.2), added a ppa repo (2.3.1.0).
Build was successful on Docker hub.

Updated Network Automation appliance

---

appliances/webterm.gns3a
docker/webterm/Dockerfile

Add ab (apache benchmark) to webterm and update the description on gns3a file.

Add ab (apache benchmark) to webterm.

---

appliances/fortiauthenticator.gns3a

Tested locally (boot, CLI, IP config, webui access), works fine.

New appliance: FortiAuthenticator

---

appliances/a10-vthunder.gns3a
appliances/windows.gns3a

Windows has been tested locally, works fine.

New appliance: Microsoft Windows (+new A10 release)

---

appliances/f5-bigip.gns3a
appliances/f5-bigiq.gns3a
docker/network_automation/Dockerfile

Container was built successfully in my personal repo.

New F5 releases & Network Automation container update

---

appliances/windows.gns3a
appliances/windows_server.gns3a
symbols/microsoft.svg
symbols/microsoft.txt

New appliance: Windows Server

---

windows_server.gns3a

David found a vhd image for 2012 R2.

Updated Windows server

---

appliances/ubuntu-gui.gns3a

User request. Tested locally, works fine.

New appliance: Ubuntu with GUI

---

appliances/ubuntu-gui.gns3a

This enables setting resolutions other than 800x600.

Added virtio vga

---

docker/openvswitch28/Dockerfile
docker/openvswitch28/LICENSE
docker/openvswitch28/README.rst
docker/openvswitch28/boot.sh

Latest image requested by community member for testing purposes.
As it is the most recent version (Not LTS), it will be subject to changes.

Image based on the latest openvswitch2.8 installed on Alpine:edge

---

appliances/fortiadc.gns3a
appliances/fortianalyzer.gns3a
appliances/fortiauthenticator.gns3a
appliances/forticache.gns3a
appliances/fortigate.gns3a
appliances/fortimail.gns3a
appliances/fortimanager.gns3a
appliances/fortisandbox.gns3a
appliances/fortisiem-super_worker.gns3a
appliances/fortiweb.gns3a
symbols/fortinet.svg
symbols/fortinet.txt

Note: Fortinet makes its icons publicly available [here](https://www.fortinet.com/resources/icon-library.html).

Added Fortinet symbol

---

appliances/cisco-nxosv.gns3a
appliances/opnsense.gns3a

Another virtual firewall. Tested locally, works fine.
If I'm not mistaken, this our 120th appliance. :)

New appliance: OPNsense

---

appliances/cisco-nxosv9k.gns3a
appliances/op5-monitor.gns3a

New appliance: OP5 Monitor

---

appliances/centos7.gns3a
docker/network_automation_pycharm/Dockerfile
docker/network_automation_pycharm/pycharm-run

Add centos appliance from osboxes.org
demo: https://www.youtube.com/watch?v=8icRLRL1ODQ
Network automation container with Pycharm
demo: https://www.youtube.com/watch?v=vCYymQzxYi8

Add centos appliance / Network automation container with Pycharm

---

appliances/brocade-vtm.gns3a
appliances/fortiauthenticator.gns3a

**My 200th commit, 300th PR for the repo!** :tada: :smiley: 
---

New Brocade VTM release

---

appliances/fortisandbox.gns3a

New FortiSandbox release

---

appliances/fortiadc.gns3a
appliances/fortigate.gns3a

New Fortinet releases

---

docker/network_automation/Dockerfile

Build and local test were successful.

Upgraded to Ansible 2.4

---

appliances/juniper-junos-space.gns3a

New appliance: Juniper Junos Space

---

README.rst
new_appliance.py

Minor fixes

---

appliances/pan-vm-fw.gns3a

Added 8.0.0 (ESX), 8.1.0 (KVM), 8.1.0 (ESX) and reordered

---

appliances/juniper-vsrx.gns3a

Fix for #314

---

appliances/net_toolbox.gns3a

New appliance: Networkers' Toolkit

---

appliances/mikrotik-chr.gns3a

Added:
- chr 6.41.4
- chr 6.40.7

MikroTik Cloud Hosted Router 6.40.7 & 6.41.4

---

appliances/mikrotik-chr.gns3a

Added new version 6.42 [currect] to top of list

New chr-6.42 version

---

appliances/network_automation.gns3a
appliances/python-go-perl-php.gns3a

Since I'm maintaining these containers, I'd switch the appliances to my repo. It's easier to do updates/testing.

Switched Docker Hub repo

---

appliances/ubuntu-cloud.gns3a

Add Ubuntu Cloud 18.04 (LTS)

---

appliances/aaa.gns3a
appliances/dns.gns3a

New appliances: AAA & DNS

---

appliances/frr.gns3a

New appliance: FRRouting

---

appliances/cumulus-vx.gns3a

New release

---

appliances/cisco-nxosv9k.gns3a

nxosv-final.7.0.3.I7.4.qcow2"
---
---

New nxosv9k version

---

appliances/cisco-asav.gns3a

New ASAv version

---

appliances/cisco-iosxrv9k.gns3a

Latest image

---

appliances/extreme-networks-voss.gns3a

Added Extreme Networks Virtual Services Platform VSP8K  VOSS
---
---
- [x ] The device is in the right category: router, switch, guest (hosts), firewall
- [x ] You filled in as much info as …

Added VOSS VSP8K switch.

---

appliances/kali-linux.gns3a

Add the latest version 2018.3
---
---

Update Kali appliance.

---

appliances/juniper-vmx-vcp.gns3a
appliances/juniper-vmx-vfp.gns3a

Add JunOS 17.3R1.10 to vMX vCP and vMX vFP

---

appliances/cisco-iosxrv9k.gns3a

New version.

---

appliances/cisco-nxosv9k.gns3a

New version

---

appliances/dell-ftos.gns3a

Provide correct appliance description - OS9/FTOS (vs. OS10)

---

appliances/fortiproxy.gns3a
appliances/frr.gns3a

Updating the **existing** appliance:
---
Creating a **new** appliance:

New appliance: FortiProxy - New release: FRR6.0

---

appliances/fortiadc-manager.gns3a
appliances/fortiadc.gns3a
appliances/fortirecorder.gns3a
appliances/mikrotik-chr.gns3a
appliances/op5-monitor.gns3a

Updating an **existing** appliance:
---
Creating a **new** appliance:

New appliances: FortiADC Manager & FortiRecorder; New releases

---

appliances/pfsense.gns3a

this template will allow to install pfSense on GNS3
---
---

Patch pfSense Appliance

---

appliances/openwrt.gns3a

add release 18.06.2

---

appliances/bsdrp.gns3a
appliances/coreos.gns3a
appliances/cumulus-vx.gns3a

---
- [X ] The new version is on top.
- [X ] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [X ] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---

Updated to latest versions

---

appliances/ipfire.gns3a
appliances/kali-linux.gns3a
ipfire.gns3a
kali-linux.gns3a

Updated IPFire and Kali

---

appliances/kali-linux.gns3a

---
---
MD5 of kali-linux-persistence-1gb.qcow2 corrected.

Kali Linux - Correct MD5 of kali-linux-persistence-1gb.qcow2

---

appliances/exos.gns3a

---
---
- [ x] You filled in as much info as possible (checks the schemas and other appliance files for some …

Added 22.7 and removed old versions of 22.x

---

appliances/cisco-iosv.gns3a

- Run check.py and no errors were reported
- Include the latest version on top of available images
- Ensure no version/filename duplicates are present
- Add image size and MD5SUM accordingly
---
---

Add last IOSv 15.7.3 version to GNS3-registry

---

appliances/cisco-asav.gns3a

ASAv version 9.12.2

---

appliances/arista-veos.gns3a

vEOS version 4.22.0F

---

appliances/cisco-nxosv9k.gns3a

NXOSv version 9.3(1)

---

appliances/cisco-csr1000v.gns3a

CSR1000v versions 16.6.6 and 16.12.1a

---

appliances/cisco-iosxrv9k.gns3a

XRv9000 versions 6.5.3 and 6.6.2

---

appliances/cisco-iosxrv9k.gns3a

Add XRv9k version 7.0.1

---

appliances/f5-bigiq.gns3a

Hi,
I would like to propose the new BIG-IQ-7.0.0.0 version:
https://downloads.f5.com/esd/serveDownload.jsp?path=/big-iq/big-iq_cm/7.0.0/english/v7.0.0/&sw=BIG-IQ&pro=big-iq_CM&ver=7.0.0&container=v7.0.0&file=BIG-IQ-7.0.0.0.0.1854.qcow2.zip

Add BIG-IQ-7.0.0.0

---

appliances/cisco-nxosv9k.gns3a

Adding Nexus 9000v Switch Release 7.0(3)I7(7)

Nexus 9000v Switch Release 7.0(3)I7(7)

---

docker/network_automation/Dockerfile

- Ubuntu 18.04 LTS
- Ansible 2.8
Build log:[Dockerfile-build-wheel.log](https://github.com/adosztal/gns3-containers/files/3639686/Dockerfile-build-wheel.log)

Upgrading versions

---

appliances/mikrotik-chr.gns3a

Fix the version and download link for mikrotik-chr 6.44.3

---

appliances/mikrotik-chr.gns3a

FIX md5 and filesice Mikrotik chr 6.44.5 and 6.45.6

---

ubuntu-server-18.04.3 (64bit) LTS.gns3a

New Ubuntu Server appliance

---

appliances/bsdrp.gns3a
appliances/cisco-dcnm.gns3a
appliances/clearos.gns3a
appliances/cumulus-vx.gns3a
appliances/exos.gns3a
appliances/fortiadc.gns3a
appliances/fortianalyzer.gns3a
appliances/fortiauthenticator.gns3a
appliances/fortigate.gns3a
appliances/fortimail.gns3a
appliances/fortimanager.gns3a
appliances/freebsd.gns3a
appliances/ipfire.gns3a
appliances/packetfence-zen.gns3a
appliances/zentyal-server.gns3a
appliances/zeroshell.gns3a
check.py

Usually when I add new releases (without new symbols), I don't wait until the script checks everything, just press Ctrl-C. Python drops errors in this case , which might be confusing for people. This small interrupt handler gives an abort message instead of the errors.

 Handling Ctrl-C 

---

schemas/appliance_v6.json

Solves #478. New section starts at line 253.

New schema for custom adapters

---

appliances/openwrt.gns3a

added version 18.06.5

---

appliances/danos.gns3a

Adding DANOS

---

appliances/extreme-networks-voss.gns3a

Upgraded CPU and Ram for v8
---
---
- [x ] You filled in as much info as possible (checks the schemas and …

Added Version 8.1

---

appliances/cisco-nxosv9k.gns3a

Added Nexus 9300v and 9500v 9.3.3

---

check.py

Just a minor update to the check.py script.

Added schema v6

---

appliances/openwrt.gns3a

update to version 18.06.6 and 19.07.0

---

appliances/mikrotik-chr.gns3a

Update Mikrotik CHR

---

appliances/debian10-min.gns3a

Hi
This is a simple and minimal Debian 10 appliance, both checks were executed and all is OK.
Also, the appliance was tested locally and runs like a charm.
Will be glad if you merge this PR into master, would be great to see Debian 10 as an option ;)
Thanks!

Debian10 minimal appliance

---

appliances/f5-bigip.gns3a

Added version 14.1.2.3-0.0.5

---

appliances/openwrt.gns3a

Update to 19.07.2 and 18.06.8

---

appliances/openwrt.gns3a

Update to version 19.07.3

---

appliances/exos.gns3a
appliances/extreme-networks-voss.gns3a

Latest versions added. Direct downloads also changed for VOSS to match our new storage location.
---
---
- [ …

Updated VOSS and EXOS

---

appliances/netem.gns3a

Domain has been updated, no other changes.
---

NETem - URL updates

---

appliances/mikrotik-chr.gns3a

---
- [ X ] The new version is on top.
- [ X  ] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
---

Update RouterOS + FIX

---

appliances/freeRouter.gns3a

please accept freeRouter appliance! thanks

adding freeRouter appliance

---

appliances/exos.gns3a

---
---
- [x ] You filled in as much info as possible (checks the schemas and other appliance files for some …

Adding EXOS 30.7.

---

appliances/openwrt.gns3a

Update version to 19.07.04

---

appliances/juniper-vqfx-pfe.gns3a
appliances/juniper-vqfx-re.gns3a

Update Juniper vQFX

---

appliances/huawei-ar1kv.gns3a
appliances/huawei-usg6kv.gns3a
appliances/ubuntu-gui.gns3a

Add HuaWei AR1000v support

---

appliances/tinycore-linux.gns3a

Hi and thanks a lot for GNS3!
I'd like to offer an improvement to the description of the Tiny Core appliance.

Fix typo in tinycore-linux.gns3a

---

appliances/huawei-ce12800.gns3a
appliances/huawei-ne40e.gns3a

Add HuaWei CE12800 & NE40E support

---

appliances/f5-bigip.gns3a

Add BIG-IP v16

---

appliances/extreme-networks-voss.gns3a

VOSS 8.2 added

---

appliances/aruba-vgw.gns3a

Added Aruba VGW GNS3a template
---
---
- [x ] The device is in the right category: router, switch, guest (hosts), firewall
- [ x] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [x ] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
- [x ] If you forked the repo, running check.py doesn't drop any errors for the …

aruba-vgw.gns3a

---

appliances/rhel.gns3a

Created Red Hat Enterprise Linux appliance, that directs you to Image download with subscription access.

Add RHEL appliance

---

appliances/openwrt.gns3a

Update to 19.07.5

---

appliances/ipxe.gns3a

Added guest booted from network via iPXE

---

appliances/openwrt.gns3a

Update to 19.07.6

---

appliances/exos.gns3a

---
---
- [ x] You filled in as much info as possible (checks the schemas and other appliance files for some …

Added EXOS 31.1

---

appliances/ubuntu-cloud.gns3a

Add Ubuntu 20.04 to ubuntu-cloud appliance, this is the latest LTS release

add Ubuntu Server 20.04 to ubuntu-cloud appliance

---

appliances/openwrt.gns3a

Update to 19.07.7

---

appliances/extreme-networks-voss.gns3a

---
---
- [ x] You filled in as much info as possible (checks the schemas and other appliance files for some …

Added VOSS 8.3

---

appliances/stonework.gns3a

---
---
- [Y] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
- [Y] GNS3 VM can run it without any tweaks.
- [Y] The device is in the right category: router, switch, guest (hosts), firewall
- [Y] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [Y] When adding a container: it builds on Docker Hub and can be pulled.
- [Y] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
- [Y] If you forked the repo, running …

Add StoneWork mini

---

appliances/vyos.gns3a

---
---
Updated 1.2 releases to v1.2.7

VyOS - update to v1.2.7

---

packer/README.rst
packer/alpine-linux/README.rst
packer/tinycore-linux/README.rst

Added a note about the packer version dependency, fixes #584.
As I'm not a native english speaker, please audit/edit my changes.

Add note about packer version dependency, fixes #584

---

appliances/kali-linux.gns3a

Added latest kali linux version 2021.1
---
---

Update to latest release of kali linux

---

appliances/cisco-iosv.gns3a

new vios-adventerprisek9-m.spa.159-3.m3.qcow2 image
---
---

adding new vIOS image

---

appliances/extreme-networks-voss.gns3a

Added VOSS 8.4 and cleaned up some spacing to make it look nice :)
---
---
- [ x] You filled in as much info …

Adding VOSS versions 8.4, and cleaned up spacing.

---

docker/dhcp/Dockerfile
docker/dhcp/README.rst
docker/dhcp/boot.sh

Update and fix typos in DHCP container

---

appliances/openwrt.gns3a

update to v. 19.07.8

---

appliances/openwrt.gns3a

update to v. 21.02.0

---

appliances/openwrt.gns3a

Update openwrt to 21.02.1

---

appliances/mikrotik-chr.gns3a

Update with mikrotil 6.48.5 - 6.49.1 - 7.1rc7

---

appliances/mikrotik-chr.gns3a

ADD test 7.1 and remove old version

---

appliances/opnsense.gns3a

Add OPNsense 21.7.1 release

---

appliances/pfsense.gns3a

Add pfSense2.5.2 release

---

appliances/aruba-arubaoscx.gns3a

Username and Password Text improved.
---
---

aruba-arubaoscx: Username and Password Text improved

---

appliances/ovs-snmp.gns3a
docker/ovs-snmp/Dockerfile
docker/ovs-snmp/README.rst
docker/ovs-snmp/boot.sh
docker/ovs-snmp/lldpd.conf
docker/ovs-snmp/rstp
docker/ovs-snmp/snmpd.conf

Added a configurable ovs with SNMPd in docker/ 
Created a appliance file.
!!!Open item:  When adding a container: it builds on Docker Hub and can be pulled.

Add docker/ovs-snmp, a SNMP enabled open vSwitch image source.

---

docker/ovs-snmp/Dockerfile
docker/ovs-snmp/boot.sh
docker/ovs-snmp/lldpd.conf

Please rebuild and push docker container gns3/ovs-snmp after merge.

ovs-snmp:  work around weird lldpd behaviour. 

---

docker/ovs-snmp/boot.sh
docker/ovs-snmp/snmpd.conf

minor improvements, please re-build and publish docker container

fix: extend SNMP view to mib-2; in boot.sh add hostname to DHCP client

---

appliances/sophos-xg.gns3a

add 18.5.2 MR2 to Sophos XG

---

appliances/opnsense.gns3a

add OPNsense 22.1.2

---

appliances/pfsense.gns3a

Adding pfSense 2.6.0 (newest release as of today)

add pfsense 2.6.0

---

appliances/vyos.gns3a

vyos - add v1.3.1

---

appliances/debian.gns3a

Debian: Update to versions 11.3 and 10.12

---

appliances/exos.gns3a

Added 31.7 image

---

appliances/cisco-iou-l3.gns3a

Add support for Cisco IOU L3 15.7(3)M2

---

appliances/juniper-vrr.gns3a

Add support for Juniper vRR 20.4R3.8-KVM

---

appliances/exos.gns3a

Adding EXOS 32.1

---

appliances/mikrotik-chr.gns3a

Update Mikrotik CHR to 6.48.6-7.4rc2

---

appliances/debian.gns3a

Debian: Update to versions 11.4

---

appliances/alpine-linux-virt.gns3a
symbols/alpine-virt-qemu.svg
symbols/alpine-virt-qemu.txt

- This appliance runs in qemu, allowing further customization of the machine and holds in ~70MB.
- Autologin is enabled as root.
- APK are configured and ready to be installed.
---

Added Alpine Linux (virt kernel)

---

appliances/fortigate.gns3a

Added Versions:
- 6.4.11
- 7.0.9
- 7.2.3
---
- [ X] The new version is on top.
- [ X] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [ X] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---
When creating a **new** appliance: N/A

Added Fortigate 6.4.11, 7.0.9, and 7.2.3

---

appliances/cisco-pyats.gns3a
docker/pyats/Dockerfile
docker/pyats/dockerfile

---
---
- [ X] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
- [X ] GNS3 VM can run it without any tweaks.
- [X ] The device is in the right category: router, switch, guest (hosts), firewall
- [ X] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [X ] When adding a container: it builds on Docker Hub and can be pulled.
- [X ] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
- [X ] If you forked the repo, …

Created docker image for running pyATS in GNS3

---

appliances/fortiadc.gns3a

---
- [ERROR] If you forked the repo, running check.py doesn't drop any errors for the updated file. `check.py` exit with error [Issue #730](https://github.com/GNS3/gns3-registry/issues/730)
- Tested import of all 3 versions on GNS3 2.2.36 (Linux client/server)

Added FortiADC 6.2.4, 7.0.4, 7.1.0

---

appliances/fortianalyzer.gns3a
appliances/fortigate.gns3a
appliances/fortimanager.gns3a

FortiGate, FortiAnalyzer, and FortiManager version additions

---

appliances/juniper-vsrx.gns3a

add Juniper vSRX 21.2R3-S4

---

appliances/opnsense.gns3a

adding opnsense v23.1

---

appliances/debian.gns3a

Debian: Update to versions 12.0 and 11.7

---

.github/bin/docker_build

Just some cleanup of the docker build script.

Docker build: Cleanup on image rebuilds

---

appliances/debian.gns3a

Debian: Update to version 12.1

---

.github/bin/docker_build

Fix bad indent in commit 65d01f8

Build system: Fix bad indent in commit 65d01f8

---

appliances/open-media-vault.gns3a

openmediavault-650

---

.github/bin/docker_build

As discussed in #814 this PR adds retry capability to docker build tool.

Docker build: Retry on communication errors

---

.github/workflows/build-docker-images.yml

Just an update to the latest actions version.

Docker build: Update actions version

---

appliances/rockylinux.gns3a

---
---
After a previous mistake I made, I am also including proof that the new images *Boot Fully*
(Maybe this should become a standard request???)

Correcting Download URL for RockyLinux 8.8 & Adding RockyLinux 9.2

---

appliances/empty-vm.gns3a

adding more empty disks to empty-vm

---

appliances/fortigate.gns3a

- Added version 7.0.13 (Released 26OCT2023)
---
---

Updated fortigate.gns3a

---

.github/bin/docker_make
.github/docker_make.md
.github/workflows/build-docker-images.yml

The build tool behaves more like make, it builds only the changed images.

Docker build tool renamed to docker_make

---

appliances/bird.gns3a

BIRDv1 - Add EOL notice

---

appliances/opnsense.gns3a

Firewalls: opensense 24.1

---

appliances/open-media-vault.gns3a

Guest: omv v7.0.32

---

appliances/cisco-iosv.gns3a

Add version 15.9(3)M8 to IOSv appliance

---

appliances/cisco-iou-l2.gns3a
appliances/cisco-iou-l3.gns3a

IOU 17.12.1

---

appliances/fortiadc.gns3a
appliances/fortianalyzer.gns3a
appliances/fortiauthenticator.gns3a
appliances/fortigate.gns3a
appliances/fortimanager.gns3a
appliances/fortiweb.gns3a

Various Fortinet Appliance version updates

---

appliances/opnsense.gns3a

adding opnsense v24.7

---

appliances/ubuntu-gui.gns3a

added ubuntu desktop 24.04

---

appliances/ubuntu-cloud.gns3a

Add Ubuntu 24.04 cloud image

---

appliances/truenas.gns3a

Untested new appliance.
Helps #915 
---
---

Add truenas

---

appliances/reactos.gns3a

fix reactos version 21

---

appliances/mikrotik-chr.gns3a

* Last 3 versions of v7
* 6.49.13 Long-Term and 6.49.17 Stable

Update mikrotik-chr.gns3a with latest versions

---

appliances/ubuntu-cloud.gns3a

Update Ubuntu cloud images checksums and links Add Ubuntu 24.10 image.

---

appliances/cisco-iou-l2.gns3a
appliances/cisco-iou-l3.gns3a

Add IOU-L3 & IOU-L2 versions 17.15.1 from CML 2.8

---

appliances/infix.gns3a

Infix is a Network Operating System (NOS) that can run both virtually (using QEMU) and on physical switches/routers.
---
---

Add new appliance: Infix

---

appliances/infix.gns3a

* Add new version 2025.01.0
* Minor cleanup in appliance file
---
---

Update appliance: Infix

---

appliances/vyos.gns3a

Update VyOS appliance definition with 1.4.1 image

---

appliances/asterfusion-vAsterNOS-6.1.gns3a

Add Asterfusion vAsterNOS 6.1

---

appliances/infix.gns3a

infix: Add new release 2025.02.0

---

appliances/infix.gns3a

Also some whitespace fixes.
---
---

infix: Add new release 2025.04.0

---

appliances/asterfusion-vAsterNOS-campus.gns3a

Delete useless versions

---

appliances/vyos.gns3a

VyOS: Added 1.4.2 version

---

appliances/vyos.gns3a

VyOS: Added 1.4.3 version

---

appliances/infix.gns3a

Also update with new documentation URL and correct description
---
---

infix: Add new release 2025.05.0
