- appliances/tinycore-linux.gns3a
- packer/tinycore-linux/README.rst
- packer/tinycore-linux/scripts/hd-install.sh
- packer/tinycore-linux/scripts/packages.sh
- packer/tinycore-linux/scripts/post_setup.sh
- packer/tinycore-linux/scripts/serial.sh
- packer/tinycore-linux/tc-4.7.7.json
- packer/tinycore-linux/tc-6.4.json
- packer/tinycore-linux/tinycore-linux.json
I named it TinyCore, but that's temporary. Maybe another name should be chosen.
Currently the packages openssh, ipv6, iptables, iproute2, tcpdump and iperf3 are added. That can easily be changed by editing packer/tinycore-linux/scripts/packages.sh .
> TinyCore packer script

- packer/tinycore-linux/scripts/hd-install-64bits.sh
- packer/tinycore-linux/scripts/openvswitch.sh
- packer/tinycore-linux/scripts/serial.sh
Changes:
- scripts/hd-install-64bits.sh: smaller syslinux-32 installation
- scripts/openvswitch.sh: load only gcc_libs, not full gcc
- scripts/openvswitch.sh: disable default network configuration with DHCP on all interfaces
- scripts/serial.sh: serial console working also with Core64
When building core64-linux.json with packer, I get this error on the start of openssh
That doesn't happen with Core 32bit. My workaround is to change "accelerator" to "kvm" (only in local copy, not on GitHub), then it works. Very strange.
> OpenSwitch update

- appliances/juniper-vsrx.gns3a
- fixes errors reported by check.py
- added version, which uses junos-vsrx-12.1X47-D20.7
- changed RAM to 1024
- added port_name_format "ge-0/0/{0}"
- added usage, without usage check.py doesn't complain, but the appliance wizard does
```
PLEASE REPORT ON https://community.gns3.com/community/software/bug
Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/gns3_gui-1.4.0.dev10-py3.5.egg/gns3/dialogs/appliance_wizard.py", line 134, in initializePage
self._appliance["usage"])
File "/usr/local/lib/python3.5/site-packages/gns3_gui-1.4.0.dev10-py3.5.egg/gns3/registry/appliance.py", line 56, in __getitem__
return self._appliance.__getitem__(key)
KeyError: 'usage'
```
> Update Juniper vSRX appliance

- packer/tinycore-linux/scripts/bird.sh
Some cleanup of the packer script. The old version works, but may break in some future versions. No need to rebuild the appliance.
> BIRD packer script cleanup

- appliances/openwrt.gns3a
OpenWRT Chaos Calmer 15.05 x86 version. I left out the x86 in the appliance name, because it's somehow the default.
Problem is, that the image is offered only compressed, what we can't directly use. In the GNS3a file the direct download URL points to the compressed file, but the image filename, filesize and md5sum is for the uncompressed image. As the user doesn't get any information, he is puzzled that he can directly download the file, but the image remains missing.
I suggest to create an optional message within the appliance, that is shown after the download and tells the user, what manual steps he has to do, to make a real image from the download file (in our case uncompress it with gunzip).
Maybe it can replace the openwrt-realview.gns3a, as they both have the same functions, just …
> OpenWRT (x86) appliance

- appliances/microsoft-windows+ie.gns3a
Add Microsoft Windows XP + IE8 appliance
It uses VMs created by Microsoft. They are not activated, so they are time limited. XP is limited to 30 days, but can be rearmed several times (I read about 4 times). For testing a windows application within GNS3 this should be fine.
> Windows XP+IE8 appliance

- appliances/microsoft-windows+ie.gns3a
Through the absolute pointer position feature of the USB tablet the VMs pointer position gets synchronized with the hosts pointer position. This results in a greatly enhanced user experience.
> Windows XP: activate absolute pointer position

- appliances/mikrotik-chr.gns3a
This is the reason I *really* want GNS3/gns3-gui#902. This appliance works fine on a Windows server, obviously with no KVM to begin with.
The images are all versioned with "(.vmdk)", because while all stable versions currently use this format, the next version (6.34, currently in RC stage) is *also* the point where MikroTik now distribute VDI images (which I plan to add as soon 6.34 is "official", alongside the VMDK versions) and zipped IMG files, which I'll be sure to add as soon as GNS3/gns3-gui#901 is a thing (at least for zip files...).
(There are also VHDX files, but since there's no Hyper-V support in GNS3 yet, and Qemu doesn't support this format - screw those...)
There isn't *supposed* to be a difference between the different disk image versions when they're from the same CHR …
> MikroTik Cloud Hosted Router appliance.

- appliances/ostinato.gns3a
- packer/tinycore-linux/README.rst
- packer/tinycore-linux/ostinato-drone.json
- packer/tinycore-linux/ostinato.json
- packer/tinycore-linux/scripts/ostinato-drone.sh
- packer/tinycore-linux/scripts/ostinato.sh
The Ostinato VM now includes the GUI That makes it much easier to use it.
I'm using Xorg instead of the normal Xvesa. The main difference is the support for an USB tablet. That automatically synchronizes the host pointer position with the VMs pointer position. That makes the usage much nicer.
It includes also packer scripts, for the full VM and a drone-only version. But I will support only the full VM.
> Ostinato with GUI

- appliances/mikrotik-chr.gns3a
Earlier today, MikroTik released a new CHR version, which comes as img, vdi, vmdk and vhdx images. This PR adds the first three.
All tested (as in "they install successfully").
> Added a new version of MikroTik CHR (6.33.5)

- appliances/fortigate.gns3a
5.4.0 has not been added yet because only an update package is available to download. Will check later.
> FortiGate appliance

- appliances/mikrotik-chr.gns3a
Also includes altering the RAM requirement to 128MiB in accordance with the new minimal requirements (installation fails otherwise).
I also noticed I made some errors in the 6.33.5 release, and this PR fixes those too.
> MikroTik CHR 6.34

- check_urls_be.py
This is not a normal pull request, as I don't expect that you merge it. It's more a way to show you my version of check_url.py
The current check_url.py has some drawbacks:
* It terminates at the first error. Sad enough there is (almost) some web site, that don't work. Therefore an error is not necessarily a problem of the registry. Currently https://www.cumulusnetworks.com seems to be down and https://dev.microsoft.com/ has an invalid certificate
* Some websites (e.g. http://www.gns3.com) refuse the connection, when the user agent is not a well-known one
* You can't check some few appliances
I decided to use pycurl, because it's rock stable, has a simple interface and creates good error messages. Drawback is, that is has to be installed ```pip3 install pycurl```.
Here the current errors, …
> Have a look at my version of check_url.py

- appliances/microsoft-windows+ie.gns3a
- check_urls.py
As dev.windows.com (and potentially some other sites) doesn't like HEAD request, check_url now uses GET requests, which will aborted as soon as some data coming in.
Furthermore changed the microsoft vendor URL to http://www.microsoft.com, which didn't work with the old check_url.
Now the check_url manages to run without errors.
> use GET requests instead of HEAD for checking URLs

- appliances/cisco-asa.gns3a
- appliances/cisco-asav.gns3a
- appliances/cisco-csr1000v.gns3a
- appliances/cisco-iosv.gns3a
- appliances/cisco-iosvl2.gns3a
It was too long and was shown as 'Gigabite' in the GUI. Basically did the same for all Cisco templates that I did for IOS-XR (as discussed in issue #100).
> Changed 'GigabitEthernet' to 'Gi'

- appliances/hp-vsr1001.gns3a
Updated the interface names too, VSR uses GE1/0 - GE16/0 instead of eth.
> New SW release for VSR1001

- appliances/untangle.gns3a
Note: an .img file is also downloadable from their site but that's just the same installer for USB drives, not a pre-installed image (plus, it's larger than the ISO file).
> Added Untangle NG firewall

- appliances/ipterm.gns3a
- appliances/webterm.gns3a
- docker/ipterm/README.md
- docker/ipterm/base/Dockerfile
- docker/ipterm/cli/Dockerfile
- docker/ipterm/web/Dockerfile
ipterm and webterm are debian based networking toolboxes using docker.
I'm using ipterm as a replacement for VPCS.
webterm is the GUI version with an additionally firefox web browser (and a display manager and a graphical terminal emulator to have a decent GUI).
Of course, I can't publish the docker images into the gns3 docker hub, that's left to the GNS3 team.
> Added ipterm and webterm

- appliances/fortiadc.gns3a
- appliances/fortimail.gns3a
- appliances/fortiweb.gns3a
- appliances/pfsense.gns3a
The reason for changed lines is that FortiADC and FortiWeb use their data/log disks the same way we use the empty_xx_G.qcow2 ones: The same empty disk is re-used for all versions.
> New Fortinet versions & pfSense fix

- appliances/ostinato.gns3a
- packer/tinycore-linux/scripts/ostinato-drone.sh
- packer/tinycore-linux/scripts/ostinato.sh
Nothing special, only ostinato is updated.
Still uses the old tinycore 6.4. I thought about v7.x, but decided against:
- only few changes compared to 6.x, mainly newer kernel
- current version is 7.1, which has an URL, which will change with release 7.2. The latest release with a stable URL is 7.0 and I don't like using a .0 release.
> update ostinato to v0.8

- docker/ipterm/README.md
- docker/ipterm/base/Dockerfile
- docker/ipterm/base/README.md
- docker/ipterm/cli/README.md
- docker/ipterm/web/Dockerfile
- docker/ipterm/web/README.md
Added some toole (curl, host, mtr and socat).
Added READMEs in the subdirectories. This should solve the issue, that the images in docker hub have no reasonable full description.
> Additional tools (curl, host, mtr, socat) for ipterm/webterm, add READMEs

- appliances/cisco-asav.gns3a
Updated to support ASAv versions 9.7.1, 9.6.2, and 9.6.1
> Updated cisco-asav appliance

- appliances/ostinato.gns3a
- packer/tinycore-linux/ostinato.json
- packer/tinycore-linux/scripts/ostinato-drone.sh
- packer/tinycore-linux/scripts/ostinato.sh
- packer/tinycore-linux/scripts/packages.sh
Add Wireshark to VM
Update TinyCore Linux to v7.2
I had to update TinyCore Linux to 7.2, as the old TinyCore 6.4 doesn't contain the wireshark package. I didn't change to TC 7.2 globally, only for the Ostinato VM. The use of 7.2 was painless, only very few packages have been renamed/deleted. So updating the other VMs should be easy. One exception is the firefox VM as the package firefox-official was removed, maybe firefox-ESR or firefox_getlatest can be used.
I added nano to the list of always installed packages, as not everyone like vi.
> Update Ostinato to v0.8, commit 97c7d79

- appliances/arista-veos.gns3a
vEOS-lab-4.18.0.vmdk does not exist on the vEOS download page. it was changed to vEOS-lab-4.18.1F.vmdk
> update arista template with the latest arista vEOS version 4.18.1F.

- appliances/hp-vsr1001.gns3a
- Some older images were not included
- I found out there were qcow2 images that I didn't notice before, so it doesn't have to be installed
- Company name was changed a while ago
- Product URL was 404, corrected it
- These images can use virtio drivers
> Recreated HP VSR1000

- appliances/pan-vm-fw.gns3a
- check.py
Updated check.py to complain, when an invalid registry version is used, fixed pan-vm-fw.gns3a.
Otherwise PR https://github.com/GNS3/gns3-registry/pull/232 has only a temporary effect.
> Enforce registry version 3 or 4

- appliances/cisco-iou-l2.gns3a
This version of IOU supports Private-VLAN, L3 EthChannel and VACLs.
> Add 15.2d version to IOU L2 appliance

- appliances/pan-vm-fw.gns3a
"I also upped the RAM, as the minimum RAM requirement for a VM-50 in PANOS 8.0.0 is 4.5GB."
> Added entries for PANOS 8.0.0

- appliances/cumulus-vx.gns3a
Add Cumulus VX 3.4.2 release and fix interface numbering (should start from swp1, not swp0).
> New Cumulus VX release

- docker/haproxy/haproxy.cfg
The statistics configuration section is added to haproxy default config file. 
Beginner users will only have to configure backend server to get a working haproxy.
> [gns3/haproxy]: Add stats section to the default configuration

- appliances/ostinato.gns3a
- packer/tinycore-linux/ostinato.json
- packer/tinycore-linux/scripts/gui.sh
- packer/tinycore-linux/scripts/ostinato-drone.sh
- packer/tinycore-linux/scripts/ostinato.sh
- packer/tinycore-linux/scripts/post_setup.sh
Updated Ostinato to v0.9
I had to use TinyCore v8.2, as the previous used version 7.2 has issues with SSL certificates.
--
---
---
> Update Ostinato to v0.9

- PULL_REQUEST_TEMPLATE.md
- appliances/sophos-utm.gns3a
- appliances/sophos-xg.gns3a
> New Sophos releases

- appliances/vyos.gns3a
+fixed the download links for older releases.
---
> New VyOS release

- PULL_REQUEST_TEMPLATE.md
- appliances/juniper-vsrx.gns3a
+added an extra check in the pull template for new appliances
---
> New vSRX releases

- docker/network_automation/Dockerfile
- docker/network_automation_pycharm/Dockerfile
From the community forum
https://gns3.com/qa/save-configuration-permanently-o
No persistence for network automation containers (CLI & PyCharm), hence the mapping of /usr directory.
Tested and packages persist GNS3 reboots as users can use /scripts for their own scripts.
-------
---
---
> Add persistency to network automation containers (CLI & PyCharm) with additional mapping of /usr

- appliances/ubuntu-cloud.gns3a
Uses the official Ubuntu cloud images from https://cloud-images.ubuntu.com as an alternative to the osboxes.org images.
> Add Ubuntu Cloud Guest appliance

- appliances/cisco-csr1000v.gns3a
- appliances/cisco-iosvl2.gns3a
- appliances/ubuntu-gui.gns3a
Adding Cisco CSR 16.6.2, 16.7.1, vIOSL2 15.2 VIRL VMDK, Ubuntu 16.04.03
CSR 16.7.1 was already there but had incorrect md5 checksum and file size (do not coincide with file on cisco.com)
---
> Add Cisco CSR 16.6.2, 16.7.1, vIOSL2 15.2 VIRL VMDK, Ubuntu 16.04.03

- appliances/vyos.gns3a
> Fixed missing VyOS 1.1.8 entry

- appliances/ubuntu-cloud.gns3a
- Update image links to point to a specific relase to avoid md5sum errors.
- Fix broken link to ubuntu-cloud-init-data.iso.
- Remove 17.04, no longer supported.
---
> Update ubuntu-cloud appliance

- appliances/pfsense.gns3a
- Removed version 2.2.6 as it is not available for download anymore under the downloads section at https://www.pfsense.org/download/?section=downloads
- Removed versions 2.3 up to 2.3.4. Version 2.3.5 should be enough(?)
- Added new release 2.4.3 meant for installation on standard storage media. As there is (not yet) an available NanoBSD image available for 2.4.3
> Removed pfSense 2.2.6 and Added pfSense 2.4.3

- appliances/cisco-csr1000v.gns3a
> Add CSR 16.8.1a

- appliances/hp-vsr1001.gns3a
---
---
No new software version, mainly updating the URLs for the documentation and download.
I verified, that the download from the new URLs still have the same length and MD5 hash.
The product_url is invalid, but I was unable to find the current product URL for VSR on the HPE website.
I added the qemu option "-machine type=pc-1.0". Without that the linux boot loader can't load the image from the hard disk, when using QEMU v2.8.1 from Debian Stretch. It shouldn't harm with earlier QEMU versions. @adosztal , are you able to verify that?
> Update appliance hp-vsr1001

- appliances/arista-ceos.gns3a
---
Image not available in Docker Hub, see below. 
---
Aristo doesn't publish the cEOS docker container on Docker Hub, so the installation is a bit unusual. It's based on the cEOS-lab-README.txt from Arista and documented in the usage:
```
Download:
Create a (free) Arista account and login.
Then navigate to Support / Software Download and download the cEOS-lab image.
Installation:
Copy the image to your GNS3VM (or other Linux) server, then run the following commands:
docker import cEOS-lab.tar.xz ceosimage:4.20.5F
echo "rm /etc/systemd/system/getty.target.wants/getty@tty1.service" | \
docker run --name=ceos-container -e CEOS=1 -e container=docker -e …
```
> Add Arista cEOS

- appliances/f5-bigiq.gns3a
Tested OK.
---
- [X ] The new version is on top.
- [X ] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [ X] If you forked the repo, running check.py doesn't drop any errors for the updated file.
> added latest Big-iq image and version

- appliances/aruba-vmc.gns3a
- [ ✔] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
- [ ✔ ] GNS3 VM can run it without any tweaks.
- [ ✔ ]  The device is in the right category: router, switch, guest (hosts), firewall
- [ ✔ ] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [ ✔ ] When adding a container: it builds on Docker Hub and can be pulled.
- [ ✔] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
--> check.py drops errors, but not for my file
> Added new definition for Aruba Virtual Mobility Controller

- appliances/turnkey-wordpress.gns3a
As of the v15.0 release of TurnKey, the TurnKey Docker container naming convention has been bought into line with the Docker "norm". I.e. TurnKey is now use the naming convention: `turnkey/APP_NAME:VERSION_TAG` e.g. `turnkey/wordpress:15.2`. Previously the version was included in the name, i.e. `turnkey/APP_NAME-VERSION:latest` e.g. `turnkey/wordpress-14.2:latest`.
The `latest` tag will always pull in the latest release version (currently v15.2 in the case of WordPress) i.e. `turnkey/wordpress:latest` is _currently_ the same as `turnkey/wordpress:15.2`. Previous versions can be specified via tag, e.g. `turnkey/wordpress:15.1`.
Please note that I don't have GNS3 installed, but would assume that this should work (it works on vanilla Docker).
> turnkey docker naming convention has changed

- appliances/cisco-iosxrv9k.gns3a
- appliances/fortigate.gns3a
- appliances/freebsd.gns3a
- appliances/freenas.gns3a
> New releases + a workaround for #1479

- appliances/arista-veos.gns3a
Move Aboot ISO from hda_disk_image to cdrom_image
Move VMDK from hdb_disk_image to hda_disk_image
Set boot_priority to "d" to boot from CD/DVD
Add Arista vEOS version 4.20.11M
Verified that v4.18.5M, v4.20.1F, v4.20.11M, v4.21.1.1F all work without tweaks when using this adjusted appliance file and GNS3 2.1.11. Earlier versions of GNS3 that contain the boot_priority bug for QEMU based appliances do have a problem with it if that is a concern.
---
- [ X] The new version is on top.
- [ X] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [ X] If you forked the repo, running check.py doesn't drop any errors for the updated file.
--- …
> Adjust arista-veos image mounts to boot from CDROM

- appliances/fortimanager.gns3a
> New release

- README.rst
- check.py
Previously `check.py` requires the installation of imagemagick. As imagemagick is a quite big package with a lot of dependencies, I'm not too enthusiastic to install it just for `check.py`.
This PR adds an internal routine to parse a SVG and calculate the image height. So imagemagick is not needed, but if it's installed, it will still be used instead of the new internal function.
So this won't break working installation, but new installations can try without imagemagick.
> Make installation of imagemagick optional

- appliances/aruba-arubaoscx.gns3a
---
---
The errors dont look like from the appliance file:
=> Check symbols
Check router_green.svg
Traceback (most recent call last):
File "check.py", line 127, in <module>
main()
File "check.py", line 120, in main
check_symbol(symbol)
File "check.py", line 105, in check_symbol
height = int(subprocess.check_output(['identify', '-format', '%h', os.path.join('symbols', symbol)], shell=False))
File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
**kwargs).stdout
File "/usr/lib/python3.6/subprocess.py", line 403, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/lib/python3.6/subprocess.py", line 709, …
> New Release - ArubaOS-CX Simulation v10.01.0001

- appliances/vpp.gns3a
- It's tested locally:
- [ X] I dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
```
[root@localhost ~]# vppctl show version
vpp v18.10-19~ga8e3001~b67 built by root on 94a8153df066 at Mon Dec 17 12:23:05 UTC 2018
```
```
--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.251/1.251/1.251/0.000 ms
```
- [X ] GNS3 VM can run it without any tweaks.
- [ X] The device is in the right category: router, switch, guest (hosts), firewall
- [ X] I filled in as much info as possible (checks the schemas and other appliance files for some guidance).
- [X ] The filenames in the "images" section are unique (to avoid appliances and/or versions …
> FD.IO VPP router/switch appliance

- check.py
- picture.py
This PR uses the picture.py module from gns3-server to get the image properties.
This has the following advantages against the current solution:
- A common code base for image handling
- Support of SVG images with height/width containing percentages
- Support for other image formats (GIF, JPEG, PNG). 
This would allow us to support these formats also for symbols (if we want).
After getting enough trust in this module, we might even drop the use of imagemagick in the future.
> Use picture.py from gns3-server to get image properties

- appliances/mininet.gns3a
Mininet creates a realistic virtual network, running real kernel, switch and application code, on a single machine (VM, cloud or native), in seconds, with a single command.
Mininet is also a great way to develop, share, and experiment with OpenFlow and Software-Defined Networking systems.
---
> Add mininet appliance

- appliances/cisco-csr1000v.gns3a
> Add CSR1000v 16.10.1b

- appliances/cisco-nxosv9k.gns3a
Added 9.2.3, 9.2.2, 7.0.3.I7.6
---
---
> New nsoxv versions

- appliances/openwrt.gns3a
Sometimes 64 MB throws error about not sufficient memory
---
---
> increase RAM to 128 MB

- appliances/frr.gns3a
The base image has been updated to Ubuntu Server 18.04, FRR to
version 7.0. Memory size was adjusted as well because the base image
does not boot with 256 MB RAM.
---
> New FRR release - for #420

- appliances/checkpoint-gaia.gns3a
patch-2
Fixed the file name/size and md5 for v77.30 based on file availibity in the website. Version 80.10 also pointing to old file name and will need further review
---
---
> checkpoint-gaia.gns3a

- appliances/exos.gns3a
Updated to add the 30.2 Image.
---
---
- [x ] The device is in the right category: router, switch, guest (hosts), firewall
- [ x] You filled in as much info as possible (checks the schemas and …
> Added 30.2 EXOS image

- appliances/ubuntu-gui.gns3a
> New Ubuntu GUI releases

- appliances/kali-linux.gns3a
---
---
This PR adds the option to use persistence to Kali Linux. If the user selects ‘Live USB Persistence’ in the boot menu the changes are stored in a disk image. On the next boot with this boot option all the changes are still present. A short note in the usage tells about that. 
**This PR needs the image file "kali-linux-persistence-1gb.qcow2", downloadable from <https://sourceforge.net/projects/gns-3/files/Qemu%20Appliances/>. As I don't have the privileges to upload there, the maintainer has to do it. The image is temporarily available from <https://www.bernhard-ehlers.de/kali-linux-persistence-1gb.qcow2>**
Furthermore this PR made some minor changes:
- Put the default 2019.2 …
> Kali Linux - add persistence

- appliances/cisco-iosvl2.gns3a
Update the lastest cisco-iosvl2 image version up to v15.2.1 on GNS3-registry. 
---
> Update the lastest cisco-iosvl2 image version up to v15.2.1

- appliances/fortigate.gns3a
---
everything is OK message recieved.
---
> added FortiOS 6.2.1 and 6.2.2 to the Fortigate gns3a appliance template

- appliances/fortisandbox.gns3a
- appliances/fortisiem-super_worker.gns3a
- appliances/fortiweb.gns3a
- appliances/juniper-vmx-vcp.gns3a
- appliances/juniper-vmx-vfp.gns3a
- appliances/juniper-vqfx-pfe.gns3a
- appliances/juniper-vqfx-re.gns3a
- appliances/juniper-vsrx.gns3a
- appliances/kali-linux.gns3a
Don't forget to merge and not re-base. ;)
---
> New releases, vSRX NIC type fix

- appliances/juniper-vqfx-re.gns3a
Though it doesn't solve the issues with 2.2.2, I'm sure the RE works with virtio.
---
> Changed NIC type to virtio

- appliances/exos.gns3a
Added images 30.3 and 30.4 and fixed the "symbol" as it caused import errors.
---
---
- [ x] You filled in as …
> Added images 30.3 and 30.4

- appliances/watchguard-fireboxv.gns3a
- appliances/watchguard-xtmv.gns3a
> New WatchGuard appliances

- appliances/cisco-asav.gns3a
1. Added current interim releases - 9.12.2 and 9.8.4
2. Updated all download URLs
3. Removed outdated and private access versions
---
> Update ASAv appliances file

- docker/kalilinux/Dockerfile
The `kali-linux-docker` image was removed from Docker Hub, so I replaced the import to the new and updated Docker image `kali-rolling`.
The `tshark` program is installed separately because if it's installed along with the remaining programs, a prompt appears and the installation process freezes.
---
> Updated Kali Linux docker image

- appliances/cisco-ise.gns3a
- Followed all instructions for editing an appliance
- Also found that ISE version 2.4.0.357 had a different MD5 sum on the download page, updated accordingly
- Updated CPU and memory requirements. Official docs state ISE version >= 2.3 requires 16 GB memory, but will boot successfully with 8GB
- Only tested version ISE 2.7 on GNS3 2.1.21
If further testing is required, please inform me and I will do so
> Update images in cisco-ise.gns3a

- appliances/cisco-csr1000v.gns3a
Added 16.12.3, 16.9.5, and 16.6.7.
Fixed a download URL pointing to the wrong version.
---
---
> Updates and URL fixes.

- appliances/kali-linux-cli.gns3a
Docker Image `gns3/kalilinux:v2` does not exist, only kali docker image that exists is `gns3/kalilinux:latest`.
> Update Appliance Kali Linux CLI

- appliances/f5-bigip.gns3a
- appliances/f5-bigiq.gns3a
Added BIG-IQ 7.1.0.0, 7.0.0.0 is no longer available for download so I've swapped it with 7.0.0.1. 5.4.0.2 is no longer available for download so its been removed. I tested BIG-IQ 7.1.0.0 with no issues.
Added BIG-IP v15.1.0.2, 15.0.1.3, and 15.0.0. Corrected filesize and m5sum for 14.1.2.3 as I had errors trying to import, fixed download URL as well. I removed 11.3 as its no longer available for download. I tested 15.1.0.2, and 14.1.2.3 with no issues.
check.py ran with no problems, output gave Everything is ok!
The diff on BIGIQ looks weird because of the line numbers changing but nothing else was modified except for the above.
---
---
- It's tested …
> Update F5 BIG-IP and BIG-IQ versions

- appliances/cisco-csr1000v.gns3a
There is an existing image called "16.6.1" so this is called "16.6.1-VIRL"
> Add csr1000v 16.6.1 image version from VIRL

- docker/jupyter/Dockerfile
- docker/jupyter/jupyter_notebook_config.py
This Pull Request is related Issue #520.
GNS3 Jupyter container can't access console.
This PR is update Python3 from 3.6.1 to 3.7.7, and add `c.NotebookApp.ip = '0.0.0.0'` line in jupyter_notebook_config.py .
---
---
> Update Jupyter container.

- appliances/frr.gns3a
- packer/alpine-linux/README.rst
- packer/alpine-linux/frr.json
- packer/alpine-linux/scripts/frr.sh
- packer/alpine-linux/scripts/serial.sh
- packer/alpine-linux/scripts/setup.sh
---
---
The current version of the FRR appliance works pretty well, but it has one main drawback: It's way too big, 717MB compressed / 2052MB uncompressed. Therefore I created a version based on alpine. It's FRR image is only 48MB "big".
I would prefer to have both versions in the appliance, but the alpine version uses network interfaces named eth0, eth1 ..., so I had to create a new one.
@adosztal It would be nice, when you would comment on this new version.
By default I enabled only the the more commonly used protocols bgp, ospf, ospf6, rip, ripng, isis, pim, ldp, eigrp, static, bfd. If the user needs the other more exotic routing protocols he has to enable it by editing the FRR …
> Reduce image size of FRR appliance

- appliances/juniper-vmx-vcp.gns3a
- appliances/juniper-vmx-vfp.gns3a
> Add new version of vMX images 20.2R1.10

- appliances/puppy-linux.gns3a
PR to fix #568 
Looks like a misplaced double quote, easy fix. Additionally, just quick fix to make the version name match the image version.
/cc @nodenineinc
> fix puppy-linux JSONDecodeError and version mismatch

- appliances/juniper-vsrx.gns3a
PR for #569 
This PR adds the following images for the Juniper vSRX appliance
* Adds 20.4R1 vSRX and vSRX 3.0
* Add 19.3R1 vSRX 3.0
* Add 18.4R3 vSRX 3.0
> juniper-vsrx: add 20.4R1, and vSRX 3.0 images

- appliances/cumulus-vx.gns3a
This PR
* Adds the latest `Cumulus VX` image version `4.3.0`
* Mentions different default login credentials depending on the version, see [What is the Default User Name and Password in Cumulus Linux? – Cumulus Networks® Knowledge Base](https://support.cumulusnetworks.com/hc/en-us/articles/201787646-What-is-the-Default-User-Name-and-Password-in-Cumulus-Linux-)
* Increases RAM for versions `>= 4` are not usable with 512M RAM, per [this note RE system requirements](https://docs.cumulusnetworks.com/cumulus-vx/KVM-QEMU/#create-the-vms-and-network-connections) 768M is the minimum.
---
> Add Cumulus VX 4.3.0, update usage, increase RAM

- appliances/fortianalyzer.gns3a
- appliances/fortigate.gns3a
- appliances/fortimanager.gns3a
This PR add the latest versions of Fortinet devices
- FortiGate version 6.4.5
- FortiManager versions 6.4.4, 6.4.5
- FortiAnalyzer version 6.4.5
Increased RAM because the latest images of FortiManager and FortiAnalyzer were
unable to boot with the current RAM specs.
---
- [ x ] The new version is on top.
- [ x ] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [ x ] If you forked the repo, running check.py doesn't drop any errors for the updated file.
> Add the latest versions of Fortinet devices

- appliances/cisco-c8000v.gns3a
- 17.04.01a image works fine on GNS3 v2.2.5
- tested with ping and cdp protocol
- works out of the box (do not click anything during GRUB boot, system will reboot once after first start )
- description, doc url, usage info has been filled
> Add Cisco Catalyst 8000V appliance

- appliances/danos.gns3a
- appliances/mcjoin.gns3a
The container mcjoin is a great tool to test multicast routing. I replaced the DANOS version with a new one because the one in the previous image was too old.
---
---
> New appliance: mcjoin; new release: DANOS

- appliances/openbsd.gns3a
When connecting devices in the GNS3 client, adapter names incorrectly show as "fxp0", "em0", "em1"..."em6"  when they should read "em0"..."em7".
---
---
> fix adapter names

- appliances/cisco-iosvl2.gns3a
new vios_l2-adventerprisek9-m.ssa.high_iron_20200929.qcow2 image
---
---
> Update to permit new vios_l2 image

- appliances/cisco-asav.gns3a
Adding addition ASAv Images as supported in CML2
---
---
> Adding addition ASAv Images

- appliances/frr.gns3a
- packer/alpine-linux/alpine.json
---
---
Updated the alpine packer script to use the current alpine version 3.14. Updated the appliance to include the newly built FRR image.
As the packer script is under the control of the GNS3 devs, I set the image location to <http://downloads.sourceforge.net/project/gns-3/Qemu%20Appliances/frr-7.5.1.qcow2>.
As I can't up upload to that location, I put it temporarily in ~~<https://www.b-ehlers.de/tmp/frr-7.5.1.qcow2>~~, @grossmj please upload it to the final location.
@grossmj Is this way of providing the image OK? Or would you like me to host the image? Any other idea???
> Update FRR to add version 7.5.1

- appliances/vyos.gns3a
---
---
Added stable version 1.2.8 and replaced the rolling release by the latest release candidate 1.3.0-rc5.
As <https://vyos.net/get/snapshots/> doesn't contain the qcow2 image for 1.3.0-rc5 I created it using the official <https://github.com/vyos/vyos-build/blob/current/scripts/build-qemu-image> script.
> vyos - add version 1.2.8 and 1.3.0-rc5

- appliances/rockylinux.gns3a
This adds Rocky Linux v8.4, a community enterprise operating system compatible with Red Hat Enterprise Linux (RHEL).
The image was built by linuxvmimages.com and will be downloaded from SourceForge.
Username: rockylinux
Password: rockylinux
To become root, use "sudo su".
---
---
> Add Rocky Linux v8.4

- appliances/vyos.gns3a
> vyos - move image 1.3.0-rc5 to MediaFire

- appliances/vyos.gns3a
The version 1.3.0-rc6 has be announced as the final release candidate for 1.3. So this should be the last image of v1.3, that is freely available. All the regular releases of vyos need a paid subscription.
Furthermore I went back to offer only official images. My self made qcow2 images are nice, but can't be verified by a third party.
@grossmj I suggest, that you check the appliances with check.py after merging them. Currently Nokia vSIM.gns3a and open-media-vault.gns3 don't meet the requirements of check.py.
---
---
---
> vyos - add v1.3.0-rc6

- docker/jupyter-2.7/Dockerfile
- docker/jupyter/Dockerfile
- docker/network_automation/Dockerfile
- docker/network_automation_pycharm/Dockerfile
using --no-cache-dir flag in pip install ,make sure downloaded packages
by pip don't cached on system . This is a best practice which make sure
to fetch from repo instead of using local cached one . Further , in case
of Docker Containers , by restricting caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.
Further , more detail information can be found at
https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
> chore : use --no-cache-dir flag to pip in dockerfiles to save space

- appliances/vyos.gns3a
VyOS published another publicly available pre-release of v1.3.0: v1.3.0-epa1, epa means “early production access”.
---
---
> vyos - add v1.3.0-epa1

- appliances/lancom-vrouter.gns3a
Good evening and thank you for GNS3!
This is my attempt at adding an appliance file ! :)
LANCOM is a german manufacturer of network appliances (router, firewall, access points, wifi controllers, ...) which run their own proprietary os named `LCOS`.
I've have seen LANCOM devices in small to medium sized german companies.
This appliance adds the virtual offering [vRouter](https://www.lancom-systems.com/products/routers-vpn-gateways/central-site-vpn-gateways/lancom-vrouter/) to GNS3.
I have already successfully used them to test something for my $dayjob.
I am not sure wether the category `router` is correct because it is also a firewall, wifi controller, VPN gateway and so on.
Also the unlicensed version of the `vRouter` limits every network interface to `1mbit/s`, only allows 1 VPN …
> add  LANCOM vRouter appliance

- appliances/rhel.gns3a
> Updated rhel.gns3a with Current RHEL 8.4 and RHEL 8.5 KVM Images

- appliances/mikrotik-chr.gns3a
- Fixed error message due to incorrect filenames
- Fixed images that were still compressed when QEMU tried to boot them
---
---
> Fix md5sum and filesize for mikrotik images

- appliances/aruba-arubaoscx.gns3a
Aruba CX OVA Version 10.06.0110, 10.07.0010, 10.08.0001 & 10.09.0002 added.
---
---
- [] GNS3 VM can run it without any tweaks.
> aruba-arubaoscx.gns3a: New Image Versions added

- appliances/vyos.gns3a
Added v1.3.0 and replaced the freely available prerelease v1.3.0-epa1 by the latest v1.3.0-epa3.
---
---
---
> vyos - add v1.3.0 and v1.3.0-epa3

- appliances/clavister-netsheild.gns3a
Adding Clavister NetShield appliance based in version 3.80
When creating a new appliance:
It's tested locally, i.e.
[X ] You dragged an instance into a project on your box, got it installed (if necessary), and did some basic network checks (ping, UI reachable, etc.).
[ X] GNS3 VM can run it without any tweaks.
[ X] The device is in the right category: router, switch, guest (hosts), firewall
[X ] You filled in as much info as possible (checks the schemas and other appliance files for some guidance).
[ N/A] When adding a container: it builds on Docker Hub and can be pulled.
[ X] The filenames in the "images" section are unique (to avoid appliances and/or versions overwriting each other).
[ X] If you forked the repo, running …
> Support for Clavister NetShield

- appliances/frr.gns3a
- packer/alpine-linux/alpine.json
- packer/alpine-linux/scripts/frr.sh
- packer/alpine-linux/scripts/gui.sh
---
---
Updated the packer files for alpine-linux to use alpine version 3.15.0, then generated an updated FRR image and appliance, now with FRR version 8.1.0.
@grossmj Please download the FRR image from <https://github.com/b-ehlers/gns3-registry/releases/download/frr/frr-8.1.0.qcow2> and upload it to SourceForge <https://sourceforge.net/projects/gns-3/files/Qemu%20Appliances/>.
> FRR: Update to version 8.1.0

- appliances/cisco-iosv.gns3a
Community: <https://gns3.com/community/featured/cisco-iosv-appliance-borked>
GNS3 issue: <https://github.com/GNS3/gns3-web-ui/issues/1275>
Fixed md5sum, uppercase characters are not allowed.
---
---
---
> Cisco IOSv - Fix md5sum

- appliances/freebsd.gns3a
Add following FreeBSD Appliances:
- FreeBSD 12.3-RELEASE amd64
- FreeBSD 13.0-RELEASE amd64
Remove following FreeBSD Appliance because they're no longer supported and available for download:
- FreeBSD 10.3-RELEASE
- FreeBSD 10.4-RELEASE
- FreeBSD 11.0-RELEASE
- FreeBSD 11.1-RELEASE
- FreeBSD 11.2-RELEASE
- FreeBSD 11.3-RELEASE
- FreeBSD 12.0-RELEASE
- FreeBSD 12.1-RELEASE
Following checks were done sucessfully:
> Update FreeBSD appliances

- appliances/ubuntu-gui.gns3a
Added 22.04, updated older versions and removed versions, that are no longer available.
22.04 shows a blank screen with "-vga virtio", so I took the second best "-vga qxl". I verified, that this setting works with all versions.
---
---
---
> Ubuntu GUI: Add 22.04, update older versions

- appliances/huawei-ar1kv.gns3a
> update Huawei AR1000v to V300R021C00SPC100T

- appliances/cisco-c8000v.gns3a
Add 17.6.1a version to Cisco Catalyst 8000v to GNS3 Appliance Registry.
---
---
- [-] GNS3 VM can run it without any tweaks. - Tested on bare metal GNS3 Server installed via PPA
- [n/a] When adding a container: it builds on Docker Hub and can be pulled.
- [n/a] *Optional: a symbol has been created for the new appliance.*
> Add 17.6.1a to cisco-8000v.gns3a

- appliances/cumulus-vx.gns3a
Update cumulus-vx.gns3a to include version 5.1.0.
---
---
When creating a **new** appliance: **N/A**
> Added Cumulus-VX 5.1.0 to appliance file

- appliances/cisco-asav.gns3a
---
- [-] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
* **Cisco Modeling Labs (Personal) v 2.4.0 has same filename as production ASAv 9.16.2**
- [-] If you forked the repo, running check.py doesn't drop any errors for the updated file.
* **Duplicate filename for cisco-asav-9-16-2.qcow2, referenced above and in #678 **
---
When creating a **new** appliance: N/A
> Added ASAv 9.16.2 (CML version) to cisco-asav.gns3a

- appliances/fortianalyzer.gns3a
- appliances/fortigate.gns3a
- appliances/fortimail.gns3a
- appliances/fortimanager.gns3a
- appliances/fortiproxy.gns3a
- appliances/fortisandbox.gns3a
- appliances/fortiweb.gns3a
Update of following Fortinet appliances:
-fortiweb -> 7.0.1 added
-fortisandbox -> 4.2.2 added
-fortiproxy -> 7.0.6 added
-fortimanager -> 7.2.1 added
-fortimail -> 7.2.1 added
-fortigate -> 7.2.1 added
-fortianalyzer -> 7.2.1 added
Images were tested locally, each appliance is reachable via ping and web interface.
---
- [ Yes ] The new version is on top.
- [ Yes ] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [ Yes ] If you forked the repo, running check.py doesn't drop any errors for the updated file.
---
> Update Fortinet appliances

- appliances/alpine-linux-virt.gns3a
- `registry_version`
- autologin on ttyS0 instead of tty1
- filesize
---
---
> Fixed many careless issues on Alpine Linux Virt

- packer/alpine-linux-virt/.gitignore
- packer/alpine-linux-virt/README.md
- packer/alpine-linux-virt/alpine.json
- packer/alpine-linux-virt/files/alpine.conf
- packer/alpine-linux-virt/files/install.sh
- packer/alpine-linux-virt/macos.json
Packer tested only on `macOS Monterey`, takes 1m12s with `hvf` accelerator.
I hope the timing will be OK on Linux too.
> Alpine Linux (Virt) packer script

- packer/debian/README.md
- packer/debian/debian-cloud-init-data.iso
- packer/debian/debian.json
- packer/debian/scripts/debian.sh
- packer/debian/scripts/post_setup.sh
- packer/debian/scripts/remove_cloud-init_network.sh
This doesn't add/change an appliance, it only creates a basic Debian packer template. It uses the official Debian cloud image as a base image.
User debian (password debian) is the root user replacement, it is allowed to run passwordless sudo.
User gns3 (password gns3) is an unprivileged user.
Currently it doesn't add much to the cloud image, so it doesn't make much sense to create an appliance from this. The idea is, to use it as a base for other appliances. 
Sorry, I don't have time to help on issue https://github.com/GNS3/gns3-registry/issues/697, but maybe this Debian packer script helps.
> Create basic Debian packer template

- appliances/vyos.gns3a
Added vyos v1.2.9, a maintenance release of the 1.2 branch.
---
---
> vyos - add v1.2.9

- packer/debian/debian.json
- packer/debian/scripts/debian.sh
- packer/debian/scripts/post_setup.sh
- packer/debian/scripts/remove_cloud-init_network.sh
Added some improvements to the Debian packer template, no appliance is affected. These improvements were inspired by  <https://github.com/giangi/frr-gns3/tree/master/debian-cloud>, many thanks for that.
- run scripts as root, no sudo needed within scripts
- add shebang to scripts
- add "set -ex" to abort scripts on error and to display commands
> Debian packer template: Improvements

- appliances/cisco-fmcv.gns3a
I wasn't able to get the vmdk file, only the qcow2.
---
> Added FMC 6.2.2 (81)

- packer/alpine-linux/README.rst
- packer/alpine-linux/alpine.json
- packer/alpine-linux/scripts/cli.sh
- packer/alpine-linux/scripts/frr.sh
- packer/alpine-linux/scripts/install.sh
- packer/alpine-linux/scripts/post_setup.sh
- packer/alpine-linux/scripts/setup.sh
This updates the packer/alpine-linux toolchain for 3.16, plus some minor improvements.
The work is done to allow to build more up-to date (frr 8.2.2) versions of the [FRRouting marketplace appliance](https://www.gns3.com/marketplace/appliances/frr) (`appliances/frr.gns3a`) which as far as I can see seem to be built from this toolchain.
I tested the manual import of a locally-built image with the same settings of the `frr.gns3a` appliance, and the image booted without issues. I only performed basic configuration tests on it.
I did not test any of the other images buildable by the toolchain. I did not see clear traces of them in the marketplace, so I guessed they were probably retired, or used only as intermediate products or local images.
In a not entirely related issue (#697) I was …
> packer/alpine-linux update to 3.16

- packer/alpine-linux/alpine.json
Currently the alpine linux is at v 3.16 and it's really simple to upgrade.
> Update alpine linux to v 3.17

- appliances/debian.gns3a
- packer/debian/debian.json
Debian: Upgrade to version 11.6
---
> Debian: Update to version 11.6

- appliances/cumulus-vx.gns3a
- appliances/windows-11-dev-env.gns3a
Added Appliance: Windows 11 Development Environment VM
Fixed appliance: cumulus-vx - Added 5.3.1 version entries to use 5.3.1 image that was from a previous PR
---
---
- [ N/A] When adding a container: it builds on Docker Hub and can be pulled.
> Added appliance: Win-11 Dev Env VM, Fixed: cumulus-vx 

- appliances/mikrotik-chr.gns3a
The latest version of Mikrotik CHR is 7.4rc2 and I have updated the versions to the latest:
* stable
* long term
* v7 stable
There is also a change in minimum memory for the v7 branch which is verified by me and the MT team to be 384 MB of ram.
Also to allow more advanced setups I have changed the number of nics from 2 to 8.
> Updated CHR versions

- appliances/fortiweb.gns3a
---
---
When creating a **new** appliance: **N/A**
> Added version 7.0.5 to FortiWeb

- appliances/dns.gns3a
- Fixed some typos and clarified portions of the "Usage Instructions"
- Added instructions to fix interface to bind to "interface=eth0"
---
- [-] The new version is on top.
- [-] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
---
> Fixed usage instructions for DNS docker appliance

- appliances/ostinato.gns3a
> Add 1.2.0 image to Ostinato appliance

- appliances/cisco-7200.gns3a
- appliances/fortiadc.gns3a
- appliances/fortianalyzer.gns3a
- appliances/fortigate.gns3a
- appliances/fortimail.gns3a
- appliances/fortimanager.gns3a
- appliances/fortiweb.gns3a
> Multiple FortiNet appliance version/usage updates, fixed C7200 .gns3a file

- appliances/cumulus-vx.gns3a
Add Cumulus VX 5.4.0 (latest), change `hda_disk_interface` to `virtio`, and up the RAM to 1GB. Latest is idling at about ~800MB
Tested the `virtio` and 1GB ram on `5.4.0`, `5.1.0` and `4.3.0` and no issues booting or working.
> add Cumulus VX 5.4.0

- appliances/vyos.gns3a
Added the QEMU/KVM images of VyOS. The -KVM versions have the advantage that they are ready to use, no installation is required. Unfortunately, VyOS only provides these images for the old 1.2.9-S1 and 1.2.9 versions. However, they are freely available.
---
---
---
> vyos - add KVM images, v1.2.9-S1 and v1.2.9

- appliances/rockylinux.gns3a
RHEL 9 guest panic's during boot with following error "Fatal glibc error: CPU does not support x86-64-v2" https://access.redhat.com/solutions/6833751
Red Hat Enterprise Linux 9 on GNS3
Rocky Linux 9 on GNS3
AlmaLinux 9 on GNS3
need Additional Settings > Options: -cpu host
---
---
> Rocky Linux 9 on GNS3 needs -cpu host

- appliances/mikrotik-winbox.gns3a
- docker/mikrotik-winbox/Dockerfile
- docker/mikrotik-winbox/README.rst
Add Mikrotik WinBox container for GNS3 based on https://github.com/alexhorner/winbox-dockerised
---
---
Images section has been left unticked as I did not include an images section, based on referencing other container JSON files
> Add Mikrotik WinBox container for GNS3

- .github/bin/docker_build
- .github/docker_build.md
- .github/workflows/build-docker-images.yml
As discussed in https://github.com/GNS3/gns3-registry/pull/767#issuecomment-1567202487:
I  added a DOCKER_REPOSITORY environment variable, that serves the current role of DOCKER_ACCOUNT. Furthermore I added a DOCKER_USERNAME that together with DOCKER_PASSWORD will be used to optionally login to the docker registry. The combined DOCKER_ACCOUNT has gone.
This works better for organizations like GNS3.
> Replace DOCKER_ACCOUNT with DOCKER_REPOSITORY and DOCKER_USERNAME

- .github/bin/docker_build
- .github/docker_build.md
- .github/workflows/build-docker-images.yml
The Docker build tool already support building and uploading to multiple registries (by using full image names), but it allows to login only into one. This PR supports to login into multiple registries.
While the changes in the tool were quite small, the workflow got quite large changes
* Each registry gets its own "Docker Login" step. If a login is not needed the step can either be commented out or the `if:` condition can be set to false.
* For the build tool the environment variables DOCKER_USERNAME and DOCKER_PASSWORD are gone, as they allow only a login for one registry. Instead multiple variables whose name are starting with "DOCKER_LOGIN" can be specified, its format is `<registry> <user> <password>`. As before these environment variables are optional and only needed for private …
> Docker build: Support logins to multiple registries

- appliances/ipterm.gns3a
- appliances/webterm.gns3a
- docker/docker_images
- docker/ipterm/README.md
- docker/ipterm/base/Dockerfile
- docker/ipterm/cli/Dockerfile
- docker/ipterm/cli/README.md
- docker/ipterm/web/Dockerfile
- docker/ipterm/web/README.md
As announced in #770 here the updated ipterm and webterm appliances. They are based on Debian 12 (Bookworm).
---
---
---
> ipterm: Update to Debian 12 (bookworm)

- appliances/bird2.gns3a
- packer/debian/README.md
- packer/debian/bird2.json
- packer/debian/debian.json
- packer/debian/scripts/bird2.sh
- packer/debian/scripts/networking.sh
- packer/debian/scripts/post_setup.sh
This is my BIRD2 appliance, based on Debian 12 (Bookworm), as announced in issue [#501](https://github.com/GNS3/gns3-registry/issues/501#issuecomment-1567466046). It replaces the outdated BIRD appliance.
I set the image location to <http://downloads.sourceforge.net/project/gns-3/Qemu%20Appliances/bird2-debian-2.0.12.qcow2>.
As I can't upload to that location, I put it temporarily in <https://github.com/b-ehlers/gns3-registry/releases/download/BIRD2/bird2-debian-2.0.12.qcow2>, @grossmj please upload it to the final location.
---
---
---
> BIRD2: New Appliance

- .github/bin/docker_build
- .github/docker_build.md
- .github/workflows/build-docker-images.yml
Finally the PR to support building and uploading Docker images to multiple registries.
The user interface got only a small change, the environment variable DOCKER_REPOSITORY may now contain a list of repositories. The name-only docker images are built and uploaded to all repositories in this list.
First the fine print:
This PR implements method #&#8203;3 from issue #772, this does just the basic stuff. I suggest to use it for some time and when we notice some limitations, it can be extended. ~~The uploaded docker image to multiple repositories is only identical, when building in the same workflow run. When the docker image is built at different times, the packages that got installed during the docker build may have changed and then the docker image differs. That only happens, when a …
> Docker build: Support building and uploading to multiple registries

- docker/chromium/Dockerfile
Community issue: <https://gns3.com/community/featured/does-the-docker-gns3-chromium-work>
The reason is, that `jess/chromium`, the base of `chromium`, runs as an unprivileged user, but doesn't create the data directory. GNS3 starts a container always as root and therefore creates non-existent volume directories with owner root. Later it switches to the unprivileged user. But this user has no permission to use this freshly created volume directory.
Workaround: Create the data directory in the Dockerfile.
---
---
---
> chromium: Create data directory in Dockerfile

- docker/docker_images
- docker/ostinato-wireshark/Dockerfile
Fix build of ostinato-wireshark docker image. Previuosly it uses the package `mesa-dri-swrast`, which is outdated since alpine v3.12 (mid 2020). The files from that package are now in the `mesa-dri-gallium` package. By using this new package the build works (at least locally) and a short test was successful.
Furthermore Wireshark.desktop was not executable, that is also fixed.
---
---
---
> ostinato-wireshark - Fix install of mesa-dri-swrast

- .github/workflows/build-docker-images.yml
Previously `sed` was used to parse the json formatted image information. This works in the actual case, because the json data is nicely formatted. But for a more robust parsing the program `jq` is far better suited. All GitHub runners include the `jq` program, not only Ubuntu, but also the Windows and macOS ones.
> Docker build: better get_image_version()

- docker/chromium/Dockerfile
- docker/chromium/README.rst
- docker/docker_images
All docker images of jess (<https://hub.docker.com/u/jess>) haven't been updated since one month. On github I created an issue https://github.com/jessfraz/dockerfiles/issues/594, but no reaction. Since more than 2 years there are no actions in this repository, so I assume it is dead.
Therefore I included the Dockerfile from https://github.com/jessfraz/dockerfiles and let it build with our build system.
A nice additional benefit is, that the base image is now the Debian image, not the constantly changing jess/chromium. It can now use the normal build options.
> chromium - Include base Dockerfile

- appliances/endhost.gns3a
- appliances/haproxy.gns3a
- docker/docker_images
- docker/haproxy/haproxy.cfg
Basic appliances for endhost and haproxy.
---
> Add endhost and haproxy appliances

- appliances/centos-cloud.gns3a
- appliances/fedora-cloud.gns3a
- appliances/rhel.gns3a
Adding Fedora Cloud 36, Fedora Cloud 37, & Fedora Cloud 38
---
- [Y] The new version is on top.
- [Y] The filenames in the "images" section are unique, to avoid appliances / version overwriting each other.
- [Y] If you forked the repo, running check.py doesn't drop any errors for the updated file.
> Updating Fedora Cloud, CentOS-Stream, & RHEL Appliance Images

- appliances/windows_server.gns3a
Adding "Windows Server 2022" to the Guest list under the "Windows Server" category 
---
> Adding Windows Server 2022

- appliances/almalinux.gns3a
- appliances/ubuntu-cloud.gns3a
Adding Ubuntu 23.04 (Lunar Lobster) and version renaming for clarity
---
> Adding Ubuntu & AlmaLinux Updates

- appliances/huawei-ce12800.gns3a
- appliances/huawei-ne40e.gns3a
Execution log:
qemu-system-x86_64: unsupported machine type
Use -machine help to list supported machines
after qemu upgrade to 6.2.0, some errors occured
> fix huawei ce12800 and ne40 unsupported machine type error

- .github/bin/docker_build
Docker treats an untagged image name as tagged with `:latest". The build system currently does just a string compare and therefore handles untagged image names and images tagged with ':latest' as different images. This PR fixes this.
> Build system: Treat untagged and tagged :latest images as the same

- appliances/openwrt.gns3a
Update hashes for openwrt-18.06.5 and openwrt-18.06.2 based hashes from download links.
---
---
> Hash Update openwrt.gns3a

- appliances/windows-11-dev-env.gns3a
Adding Windows-11-Dev-Env - 2308
---
---
> Adding Windows-11-Dev-Env - 2308

- appliances/windows-11-dev-env.gns3a
correcting the filezise of the "WinDev2308Eval-disk1.vmdk" from my PR GNS3#811
I had an incorrect `filesize` reference in my previous PR, the `md5sum` is correct, just the `filesize` was wrong.
Sorry for the inconvenience
---
> correcting the filezise of the "WinDev2308Eval-disk1.vmdk"

- appliances/vyos.gns3a
As direct downloads from s3-us.vyos.io are no longer working, the corresponding `direct_download_url` entries have to go. The (very old) version 1.1.8 was only available via direct download, so this version is no longer available.
---
---
---
> vyos - direct download from s3-us.vyos.io no longer working

- appliances/almalinux.gns3a
- appliances/centos-cloud.gns3a
- appliances/rhel.gns3a
Fixed issue #818, add option "-cpu host" to RedHat 9 based appliances.
Replaced the Stream-9 image of the centos-cloud appliance to an image, that is available, updated the usage instruction.
@Da-Geek - While it's nice, that you update appliances, please check that your updates are working.
---
---
---
> RedHat 9 based appliances - add option "-cpu host"

- appliances/vyos.gns3a
Because the download links to the legacy releases on <https://vyos.net/get/> were no longer working, I removed them in PR #815. Today I stumbled across another download location on <https://support.vyos.io/en/support/solutions/articles/103000099217-vyos-1-2-9-s1>, that actually works. So I am able to re-add the direct download locations of the legacy releases.
---
---
---
> vyos - download of legacy releases from legacy-lts-images.vyos.io

- .github/bin/docker_build
Previously, the git commit time was used as the modification time of a file. But that's not the time a file enters this repository, it normally gets active with a pull request. Therefore, this PR additionally takes into account the time of the pull request.
> Docker build: Include time of pull request to calculation of change time

- appliances/openwrt.gns3a
Adding OpenWrt v23.05.0
---
---
> Adding OpenWrt 23.05.0

- appliances/empty-vm.gns3a
Correcting an md5sum conflict in `empty-vm.gns3a` noticed running check.py for PR #831
---
> Correcting an md5sum conflict in `empty-vm.gns3a` noticed running check.py for PR #831

- appliances/mikrotik-chr.gns3a
> Adding CHR v7.11.2 & v6.49.10

- .github/bin/docker_build
- .github/workflows/build-docker-images.yml
The definition of DOCKER_REPOSITORY in the Docker workflow is quite complex as YAML doesn't allow comments inside scalars, as they can't be distinguished from data.
This PR allows comments in the DOCKER_REPOSITORY definition. They are filtered out in the first statement of the `run` script.
> Docker build: Simplify definition of DOCKER_REPOSITORY

- appliances/huawei-ne40e.gns3a
Huawei NE40 interface renaming
=========
Updated Huawei NE40E interface naming, since current naming was off-by-one in interface numbers (2nd interface is management interface for this image and shouldn't be used).
BR 
---
---
> fix huawei ne40e interfaces

- docker/ostinato-wireshark/Dockerfile
> ostinato-wireshark: No need to use edge repository since alpine 3.19

- appliances/cisco-asav.gns3a
- appliances/cisco-c8000v.gns3a
- appliances/cisco-csr1000v.gns3a
- appliances/cisco-iosxrv9k.gns3a
- appliances/cisco-nxosv9k.gns3a
---
-- Long standing version mismatch error reported by check.py on asav.gns3a for version 9.16.2 CML (irrelevant to this PR as it add 9.18.2.
---
> Updated Cisco appliance versions for CML 2.6

- appliances/debian.gns3a
- packer/debian/debian.json
Update Debian to version 12.4
@grossmj
As the image is created by packer, it has to be build and then uploaded to <https://downloads.sourceforge.net/project/gns-3/Qemu%20Appliances/debian-12.4.qcow2>. If you build the image yourself, the size and md5sum in the appliance has to be adapted. If you like to use my build, you can get it from <https://github.com/b-ehlers/gns3-registry/releases/download/debian-12.4/debian-12.4.qcow2>.
Debian tells us:
> Please note that the point release does not constitute a new version of Debian 12 but only updates some of the packages included. 
Therefore this version 12.4 replaces 12.2. The old debian-12.2.qcow2 can be deleted when the updated appliance has reached (almost) all of the GNS3 installations, perhaps in a few months.
---
Before submitting a pull …
> Debian: Update to version 12.4

- appliances/ostinato.gns3a
Unable to install `pycurl==7.44.1` (required by `check.py`) on both Windows 10 and Ubuntu 22.04
> Add Ostinato version 1.3.0

- appliances/fedora-cloud.gns3a
> Adding Fedora Cloud 39, and removing EOL 35, 36, & 37

- appliances/rhel.gns3a
> Adding Red Hat Enterprise Linux 9.3 KVM Guest Image

- appliances/rockylinux.gns3a
---
** Version 9.3 is on top, but the new Version 8.9 is "in-line" between 8.8 & 9.2
> Adding Rocky GenericCloud-Base 8.9 & 9.3

- appliances/bird2.gns3a
- packer/debian/bird2.json
- packer/debian/scripts/networking.sh
Update of the BIRD2 appliance to v2.14.
I set the image location to <https://sourceforge.net/projects/gns-3/files/Qemu%20Appliances/bird2-debian-2.14.qcow2>.
As I can't upload to that location, I put it temporarily in <https://github.com/b-ehlers/gns3-registry/releases/download/bird2/bird2-debian-2.14.qcow2>, @grossmj please upload it to the final location.
---
---
---
> BIRD2: add version 2.14

- .github/workflows/build-docker-images.yml
This PR runs actions on git push / PR merges **only** when files in the `docker` directory have changed.
This will reduce the number of Action runs, as updating non-Docker appliances won't run the Docker build action.
> Docker build: Run push action only on changes within docker directory

- appliances/fortianalyzer.gns3a
- appliances/fortigate.gns3a
- appliances/fortimanager.gns3a
- appliances/mikrotik-rb1100ahx4-dude-edition.gns3a
- appliances/mikrotik-rb450g.gns3a
- appliances/mikrotik-rb450gx4.gns3a
---
---
fortianalyzer.gns3a & fortimanager.gns3a:
+ 6.4.14
+ 7.0.11
+ 7.4.2
fortigate.gns3a:
+ 6.4.15
+ 7.0.14
+ 7.2.7
+ 7.4.3
Changed appliance version 5->4 for 3 different mikrotik appliances that were throwing warnings from check.py.
> Updates to various FortiProducts (ref #858) and check.py fixes

- appliances/freebsd.gns3a
Added Release 14.0 and point past release links to archives link.
---
---
> Add FreeBSD Release 14.0 and Update Past Release Links

- appliances/mikrotik-chr.gns3a
I added the MikroTik CHR with version 7.14.2.
Please merge my PR to make this available to the community.
Procedure:
Downloaded .img file from MikroTik Website
Verify downloaded zip: `sha256sum chr-7.14.2.img.zip` Extract contents: `unzip sha256sum chr-7.14.2.img.zip` Get MD5 Hash: `md5sum chr-7.14.2.img`
Get Filesize: `du -sb ./chr-7.14.2.img`
Added information to mikrotik-chr.gns3a
---
---
> Adding CHR v7.14.2

- docker/docker_images
As noted in https://github.com/GNS3/gns3-registry/issues/879, the `pyats` docker image currently fails to build. Therefore its automatic build needs to be disabled.
> pyats - Disable building Docker image

- docker/openvswitch/init.sh
This PR allows to use /etc/network/interfaces to setup the IP configuration for the bridge interfaces (br0, br1, ...).
Only the bridge interfaces should not be marked as `auto` interfaces, as at the the time the initial IP configuration is applied these bridge interfaces don't exist. Therefore this would result in a (harmless) warning.
Here an example, there is nothing special:
```
#auto br0
iface br0 inet static
address 10.1.1.1
netmask 255.255.255.0
```
Furthermore the name of the bridge interface are not fixed, they are retrieved from the database. That makes the initialization of the bridge interfaces more flexible.
> openvswitch - IP configuration for bridge interfaces

- appliances/debian.gns3a
- packer/debian/debian-11.json
- packer/debian/debian.json
- packer/debian/scripts/networking.sh
On version 12.6 I removed `netplan`, as it doesn't seem to work well with `resolvconf`. Anyway, the appliance was made for using `ifupdown`.
@grossmj If you like to use my images, download them from <https://github.com/b-ehlers/gns3-registry/releases/tag/debian> and upload them to <https://sourceforge.net/projects/gns-3/files/Qemu%20Appliances/>. Otherwise you can build the images yourself with packer, then you have to adapt the size and md5sum in the appliance.
---
---
---
> Debian: Update to versions 12.6 and 11.10, remove netplan

- check.py
- schemas/appliance_v8.json
Schema v8 is invalid, the "properties" starting in line 570 end in line 724, so "images" and "versions" are no allowed properties. Therefore check.py of the v8 full example from the README.md complain with:
`jsonschema.exceptions.ValidationError: Additional properties are not allowed ('images', 'versions' were unexpected)`
The "images" and "versions" definitions must be moved up one level to put them under "properties".
Futhermore check.py checks "md5sum" of the images. With v8 "md5sum" is renamed to "checksum", so accessing the "md5sum" entry will fail for appliances using "checksum".
> Fix appliance schema v8, adapt check.py for schema v8

- appliances/security-onion.gns3a
I currently cannot make it work, I get a kernel panic when booting the appliance and trying to install it.
> Update Security Onion appliance

- appliances/almalinux.gns3a
Move AlmaLinux download links to vault.almalinux.org as files are no longer available from repo.almalinux.org
---
> Update AlmaLinux Application Links

- appliances/vyos.gns3a
---
---
```
$ python3 check.py | grep vyos
Check vyos.gns3a
Check vyos.svg
```
> Update VyOS appliance

- appliances/nixos.gns3a
This GNS3 appliance enables dynamic hostname configuration for NixOS by passing the VM name to QEMU via `-fw_cfg name=opt/vm_hostname,string=%vm-name%`, then retrieving the value during NixOS initialization. A systemd job in the system's `configuration.nix` uses this value to override the hostname, providing clear and automated naming setups in lab environments. Users are encouraged to build their own qcow2 images using [`nixos-generators`](https://github.com/nix-community/nixos-generators) for further customization.
- **Dynamic Hostname**: Automatically assigns the GNS3 instance name as the VM hostname for clear identification in lab setups.  
- **Custom Builds**: Users can build their own qcow2 images with [`nixos-generators`](https://github.com/nix-community/nixos-generators) as …
> Add GNS3 appliance for NixOS

- appliances/fortianalyzer.gns3a
- appliances/fortigate.gns3a
- appliances/fortimanager.gns3a
> Updating fortimanager, fortianalyzer, and fortigate appliance files for latest 7.4.x

- appliances/arista-veos.gns3a
Arista recommends 64bit instead of 32bit versions of vEOS https://www.arista.com/en/cg-veos-router/veos-router-dpdk-mode
---
> Update Arista vEOS to recent images and 64bit

- appliances/rhel.gns3a
---
All 4 new versions boot fine in GNS3 v2.2.53
> Adding RHEL-8.9, RHEL-8.10, RHEL-9.4, & RHEL-9.5

- appliances/fedora-cloud.gns3a
---
Both Images boot fully and can be logged into in GNS3 v2.2.53
> Adding FedoraCloud-40, & FedoraCloud-41

- appliances/almalinux.gns3a
- appliances/oracle-linux-cloud.gns3a
- appliances/rockylinux.gns3a
---
The PR is for:-
AlmaLinux-8.9
AlmaLinux-9.4
RockyLinux-9.5
Oracle Linux Cloud Images 8.10
Oracle Linux Cloud Images 9.5
All 5 Images have been Booted and Logged into locally using GNS3 v2.2.58
> Adding Updated Alma, Rocky, & Oracle Cloud Images
